<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"
	style="background:#f5f7f8">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=device-width">
		<title>Smiles Davis, you spent $9,628.32 more than last week. See
			details</title>
		<style name="sass" type="text/css">
@media only screen and (max-width:608px) {
	.body-total {
		min-width: 100vw
	}
}

@media only screen and (max-width:608px) {
	center {
		padding: 12px !important;
		-moz-box-sizing: border-box;
		-webkit-box-sizing: border-box;
		box-sizing: border-box
	}
}

@media only screen {
	html {
		min-height: 100%;
		width: 100%;
		background: #f5f7f8
	}
}

@media only screen and (max-width:608px) {
	.hide-for-large {
		display: block !important;
		width: auto !important;
		overflow: visible !important;
		max-height: none !important;
		font-size: inherit !important;
		line-height: inherit !important
	}
}

@media only screen and (max-width:608px) {
	table.body table.container .hide-for-large, table.body table.container .row.hide-for-large
		{
		display: table !important;
		width: 100% !important
	}
}

@media only screen and (max-width:608px) {
	table.body table.container .callout-inner.hide-for-large {
		display: table-cell !important;
		width: 100% !important
	}
}

@media only screen and (max-width:608px) {
	table.body table.container .show-for-large {
		display: none !important;
		width: 0;
		mso-hide: all;
		overflow: hidden
	}
}

@media only screen {
	a[x-apple-data-detectors] {
		color: inherit !important;
		text-decoration: none !important;
		font-size: inherit !important;
		font-family: inherit !important;
		font-weight: inherit !important;
		line-height: inherit !important
	}
}

@media only screen and (max-width:608px) {
	.menu.small-vertical .menu-item {
		padding-left: 0 !important;
		padding-right: 0 !important
	}
}

@media only screen and (max-width:608px) {
	table.body img {
		width: auto;
		height: auto
	}
	table.body center {
		min-width: 0 !important
	}
	table.body .container {
		width: 100% !important
	}
	table.body .column, table.body .columns {
		height: auto !important;
		-moz-box-sizing: border-box;
		-webkit-box-sizing: border-box;
		box-sizing: border-box
	}
	td.small-1, th.small-1 {
		display: inline-block !important;
		width: 8.33333% !important
	}
	td.small-2, th.small-2 {
		display: inline-block !important;
		width: 16.66667% !important
	}
	td.small-3, th.small-3 {
		display: inline-block !important;
		width: 25% !important
	}
	td.small-4, th.small-4 {
		display: inline-block !important;
		width: 33.33333% !important
	}
	td.small-5, th.small-5 {
		display: inline-block !important;
		width: 41.66667% !important
	}
	td.small-6, th.small-6 {
		display: inline-block !important;
		width: 50% !important
	}
	td.small-7, th.small-7 {
		display: inline-block !important;
		width: 58.33333% !important
	}
	td.small-8, th.small-8 {
		display: inline-block !important;
		width: 66.66667% !important
	}
	td.small-9, th.small-9 {
		display: inline-block !important;
		width: 75% !important
	}
	td.small-10, th.small-10 {
		display: inline-block !important;
		width: 83.33333% !important
	}
	td.small-11, th.small-11 {
		display: inline-block !important;
		width: 91.66667% !important
	}
	td.small-12, th.small-12 {
		display: inline-block !important;
		width: 100% !important
	}
	.column td.small-12, .column th.small-12, .columns td.small-12, .columns th.small-12
		{
		display: block !important;
		width: 100% !important
	}
	table.body td.small-offset-1, table.body th.small-offset-1 {
		margin-left: 8.33333% !important;
		Margin-left: 8.33333% !important
	}
	table.body td.small-offset-2, table.body th.small-offset-2 {
		margin-left: 16.66667% !important;
		Margin-left: 16.66667% !important
	}
	table.body td.small-offset-3, table.body th.small-offset-3 {
		margin-left: 25% !important;
		Margin-left: 25% !important
	}
	table.body td.small-offset-4, table.body th.small-offset-4 {
		margin-left: 33.33333% !important;
		Margin-left: 33.33333% !important
	}
	table.body td.small-offset-5, table.body th.small-offset-5 {
		margin-left: 41.66667% !important;
		Margin-left: 41.66667% !important
	}
	table.body td.small-offset-6, table.body th.small-offset-6 {
		margin-left: 50% !important;
		Margin-left: 50% !important
	}
	table.body td.small-offset-7, table.body th.small-offset-7 {
		margin-left: 58.33333% !important;
		Margin-left: 58.33333% !important
	}
	table.body td.small-offset-8, table.body th.small-offset-8 {
		margin-left: 66.66667% !important;
		Margin-left: 66.66667% !important
	}
	table.body td.small-offset-9, table.body th.small-offset-9 {
		margin-left: 75% !important;
		Margin-left: 75% !important
	}
	table.body td.small-offset-10, table.body th.small-offset-10 {
		margin-left: 83.33333% !important;
		Margin-left: 83.33333% !important
	}
	table.body td.small-offset-11, table.body th.small-offset-11 {
		margin-left: 91.66667% !important;
		Margin-left: 91.66667% !important
	}
	table.body table.columns td.expander, table.body table.columns th.expander
		{
		display: none !important
	}
	table.body .right-text-pad, table.body .text-pad-right {
		padding-left: 10px !important
	}
	table.body .left-text-pad, table.body .text-pad-left {
		padding-right: 10px !important
	}
	table.menu {
		width: 100% !important
	}
	table.menu td, table.menu th {
		width: auto !important;
		display: inline-block !important
	}
	table.menu.small-vertical td, table.menu.small-vertical th, table.menu.vertical td,
		table.menu.vertical th {
		display: block !important
	}
	table.menu[align=center] {
		width: auto !important
	}
	table.button.small-expand, table.button.small-expanded {
		width: 100% !important
	}
	table.button.small-expand table, table.button.small-expanded table {
		width: 100%
	}
	table.button.small-expand table a, table.button.small-expanded table a {
		text-align: center !important;
		width: 100% !important;
		padding-left: 0 !important;
		padding-right: 0 !important
	}
	table.button.small-expand center, table.button.small-expanded center {
		min-width: 0
	}
}

@media only screen and (max-width:608px) {
	.small-float-center {
		margin: 0 auto !important;
		float: none !important;
		text-align: center !important
	}
	.small-text-center {
		text-align: center !important
	}
	.small-text-left {
		text-align: left !important
	}
	.small-text-right {
		text-align: right !important
	}
}

@media only screen and (max-width:608px) {
	th.small-align-left>table>tr>th>table {
		float: left !important
	}
}

@media only screen and (max-width:608px) {
	.p-0 {
		padding: 0 !important
	}
	.pv-0 {
		padding-top: 0 !important;
		padding-bottom: 0 !important
	}
	.pt-0 {
		padding-top: 0 !important
	}
	.pb-0 {
		padding-bottom: 0 !important
	}
	.ph-0 {
		padding-left: 0 !important;
		padding-right: 0 !important
	}
	.pl-0 {
		padding-left: 0 !important
	}
	.pr-0 {
		padding-right: 0 !important
	}
	.p-1 {
		padding: 6px !important
	}
	.pv-1 {
		padding-top: 6px !important;
		padding-bottom: 6px !important
	}
	.pt-1 {
		padding-top: 6px !important
	}
	.pb-1 {
		padding-bottom: 6px !important
	}
	.ph-1 {
		padding-left: 6px !important;
		padding-right: 6px !important
	}
	.pl-1 {
		padding-left: 6px !important
	}
	.pr-1 {
		padding-right: 6px !important
	}
	.p-2 {
		padding: 12px !important
	}
	.pv-2 {
		padding-top: 12px !important;
		padding-bottom: 12px !important
	}
	.pt-2 {
		padding-top: 12px !important
	}
	.pb-2 {
		padding-bottom: 12px !important
	}
	.ph-2 {
		padding-left: 12px !important;
		padding-right: 12px !important
	}
	.pl-2 {
		padding-left: 12px !important
	}
	.pr-2 {
		padding-right: 12px !important
	}
	.p-3 {
		padding: 18px !important
	}
	.pv-3 {
		padding-top: 18px !important;
		padding-bottom: 18px !important
	}
	.pt-3 {
		padding-top: 18px !important
	}
	.pb-3 {
		padding-bottom: 18px !important
	}
	.ph-3 {
		padding-left: 18px !important;
		padding-right: 18px !important
	}
	.pl-3 {
		padding-left: 18px !important
	}
	.pr-3 {
		padding-right: 18px !important
	}
	.p-4 {
		padding: 24px !important
	}
	.pv-4 {
		padding-top: 24px !important;
		padding-bottom: 24px !important
	}
	.pt-4 {
		padding-top: 24px !important
	}
	.pb-4 {
		padding-bottom: 24px !important
	}
	.ph-4 {
		padding-left: 24px !important;
		padding-right: 24px !important
	}
	.pl-4 {
		padding-left: 24px !important
	}
	.pr-4 {
		padding-right: 24px !important
	}
	.p-5 {
		padding: 30px !important
	}
	.pv-5 {
		padding-top: 30px !important;
		padding-bottom: 30px !important
	}
	.pt-5 {
		padding-top: 30px !important
	}
	.pb-5 {
		padding-bottom: 30px !important
	}
	.ph-5 {
		padding-left: 30px !important;
		padding-right: 30px !important
	}
	.pl-5 {
		padding-left: 30px !important
	}
	.pr-5 {
		padding-right: 30px !important
	}
}
</style>

</head>
<body class="body-total"
	style="-moz-box-sizing: border-box; -ms-text-size-adjust: 100%; -webkit-box-sizing: border-box; -webkit-text-size-adjust: 100%; Margin: 0; background: #f5f7f8; box-sizing: border-box; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0; padding: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; width: 100% !important">
	<span class="preheader"
		style="color: #f5f7f8; display: none !important; font-size: 1px; line-height: 1px; max-height: 0; max-width: 0; mso-hide: all !important; opacity: 0; overflow: hidden; visibility: hidden"></span>
	<table class="body"
		style="Margin: 0; background: 0 0; border-collapse: collapse; border-spacing: 0; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; height: 100%; line-height: 150%; margin: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
		<tr
			style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
			<td class="center" align="center" valign="top"
				style="-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; hyphens: auto; line-height: 150%; margin: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; word-wrap: break-word">
				<center data-parsed="" style="min-width: 600px; width: 100%">
					<table class="spacer float-center"
						style="Margin: 0 auto; border-collapse: collapse; border-spacing: 0; float: none; margin: 0 auto; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: center; vertical-align: top; width: 100%">
						<tbody>
							<tr
								style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
								<td height="24px"
									style="-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 24px; font-weight: 400; hyphens: auto; line-height: 24px; margin: 0; mso-line-height-rule: exactly; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; word-wrap: break-word">&#xA0;</td>
							</tr>
						</tbody>
					</table>
					<table bgcolor="#FFFFFF" align="center" class="container card"
						style="Margin: 0 auto; background: 0 0; border-collapse: collapse; border-spacing: 0; margin: 0 auto; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: inherit; vertical-align: top; width: 600px">
						<tbody>
							<tr
								style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
								<td
									style="-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; background: #fefefe !important; border-collapse: collapse !important; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; hyphens: auto; line-height: 150%; margin: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; word-wrap: break-word">
									<table class="spacer bg-dark-blue"
										style="background-color: #173049; border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
										<tbody>
											<tr
												style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
												<td height="8px"
													style="-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 8px; font-weight: 400; hyphens: auto; line-height: 8px; margin: 0; mso-line-height-rule: exactly; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; word-wrap: break-word">&#xA0;</td>
											</tr>
										</tbody>
									</table>
									<table class="row bg-pie-chart"
										style="background-position: top right; background-repeat: no-repeat; background-size: 177px 182px; border-collapse: collapse; border-spacing: 0; display: table; padding: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; position: relative; text-align: left; vertical-align: top; width: 100%">
										<tbody>
											<tr
												style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
												<th class="p-4 small-12 large-12 columns first last"
													style="Margin: 0 auto; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0 auto; padding: 32px; text-align: left; width: 592px">
													<table
														style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
														<tr
															style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
															<th
																style="Margin: 0; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0; text-align: left"><img
																class="logo-icon"
																src="<?php echo $logo; ?>"
																width="64" height="64"
																style="-ms-interpolation-mode: bicubic; clear: both; display: block; height: 64px; max-width: 100%; outline: 0; text-decoration: none; width: 64px">
																	<table class="spacer"
																		style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
																		<tbody>
																			<tr
																				style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
																				<td height="24px"
																					style="-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 24px; font-weight: 400; hyphens: auto; line-height: 24px; margin: 0; mso-line-height-rule: exactly; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; word-wrap: break-word">&#xA0;</td>
																			</tr>
																		</tbody>
																	</table>
																	<h1 class="text"
																		style="Margin: 0; Margin-bottom: 4px; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 32px; font-weight: 700; line-height: 150%; margin: 0; margin-bottom: 4px; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; word-wrap: normal">Hi
																		<?php echo $customer; ?>,</h1>
																	<h3 class="text regular"
																		style="Margin: 0; Margin-bottom: 4px; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 20px; font-weight: 400 !important; line-height: 150%; margin: 0; margin-bottom: 4px; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; word-wrap: normal">
																		Recipt for Trip <span class="bold"
																			style="font-weight: 600 !important"><?php echo strtoupper($bookingUid)?></span>
																	</h3></th>
															<th class="expander"
																style="Margin: 0; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0; padding: 0 !important; text-align: left; visibility: hidden; width: 0"></th>
														</tr>
													</table>
												</th>
											</tr>
										</tbody>
									</table>
									<table class="row"
										style="border-collapse: collapse; border-spacing: 0; display: table; padding: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; position: relative; text-align: left; vertical-align: top; width: 100%">
										<tbody>
											<tr
												style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
												<th class="pl-4 pr-2 small-6 large-6 columns first"
													style="Margin: 0 auto; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0 auto; padding-left: 32px; padding-right: 16px; text-align: left; width: 292px">
													<table
														style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
														<tr
															style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
															<th
																style="Margin: 0; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0; text-align: left">
																<div
																	style="height: 90px; position: relative; width: 65px">
																	<div style="width: 100%; position: absolute; bottom: 0">
																		<div
																			style="width: 100%; height: 18px; background-color: #9fd1ff"></div>
																		<div
																			style="width: 100%; height: 30px; background-color: #007ef2"></div>
																	</div>
																</div>
															</th>
														</tr>
													</table>
												</th>
												<th class="pl-2 pr-4 small-6 large-6 columns last"
													style="Margin: 0 auto; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0 auto; padding-left: 16px; padding-right: 32px; text-align: left; width: 292px">
													<table
														style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
														<tr
															style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
															<th
																style="Margin: 0; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0; text-align: left">
																<div
																	style="height: 90px; position: relative; width: 65px">
																	<div style="width: 100%; position: absolute; bottom: 0">
																		<div
																			style="width: 100%; height: 70px; background-color: #9fd1ff"></div>
																		<div
																			style="width: 100%; height: 20px; background-color: #007ef2"></div>
																	</div>
																</div>
															</th>
														</tr>
													</table>
												</th>
											</tr>
										</tbody>
									</table>
									<table class="row"
										style="border-collapse: collapse; border-spacing: 0; display: table; padding: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; position: relative; text-align: left; vertical-align: top; width: 100%">
										<tbody>
											<tr
												style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
												<th class="pt-4 pr-2 pl-4 small-6 large-6 columns first"
													style="Margin: 0 auto; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0 auto; padding-left: 32px; padding-right: 16px; padding-top: 32px; text-align: left; width: 292px">
													<table
														style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
														<tr
															style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
															<th
																style="Margin: 0; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0; text-align: left">
																<h6 class="badge pb-0"
																	style="Margin: 0; Margin-bottom: 4px; color: inherit; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 12px; font-weight: 600 !important; letter-spacing: 1px; line-height: 150%; margin: 0; margin-bottom: 4px; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; text-transform: uppercase; word-wrap: normal">Estimated
																	Trip</h6>
															</th>
														</tr>
													</table>
												</th>
												<th class="pt-4 pl-2 pr-4 small-6 large-6 columns last"
													style="Margin: 0 auto; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0 auto; padding-left: 16px; padding-right: 32px; padding-top: 32px; text-align: left; width: 292px">
													<table
														style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
														<tr
															style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
															<th
																style="Margin: 0; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0; text-align: left">
																<h6 class="badge pb-0"
																	style="Margin: 0; Margin-bottom: 4px; color: inherit; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 12px; font-weight: 600 !important; letter-spacing: 1px; line-height: 150%; margin: 0; margin-bottom: 4px; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; text-transform: uppercase; word-wrap: normal">Actual
																	Trip</h6>
															</th>
														</tr>
													</table>
												</th>
											</tr>
										</tbody>
									</table>
									<table class="row"
										style="border-collapse: collapse; border-spacing: 0; display: table; padding: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; position: relative; text-align: left; vertical-align: top; width: 100%">
										<tbody>
											<tr
												style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
												<th class="pr-2 pl-4 small-6 large-6 columns first"
													style="Margin: 0 auto; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0 auto; padding-left: 32px; padding-right: 16px; text-align: left; width: 292px">
													<table
														style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
														<tr
															style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
															<th
																style="Margin: 0; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0; text-align: left">
																<h1 style="Margin: 0; Margin-bottom: 4px; color: inherit; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 32px; font-weight: 700; line-height: 150%; margin: 0; margin-bottom: 4px; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; word-wrap: normal"></h1>
															</th>
														</tr>
													</table>
												</th>
												<th class="pl-2 pr-4 small-6 large-6 columns last"
													style="Margin: 0 auto; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0 auto; padding-left: 16px; padding-right: 32px; text-align: left; width: 292px">
													<table
														style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
														<tr
															style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
															<th
																style="Margin: 0; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0; text-align: left">

															</th>
														</tr>
													</table>
												</th>
											</tr>
										</tbody>
									</table>
									<table class="row"
										style="border-collapse: collapse; border-spacing: 0; display: table; padding: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; position: relative; text-align: left; vertical-align: top; width: 100%">
										<tbody>
											<tr
												style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
												<th class="pr-2 pl-4 small-6 large-6 columns first"
													style="Margin: 0 auto; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0 auto; padding-left: 32px; padding-right: 16px; text-align: left; width: 292px">
													<table
														style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
														<tr
															style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
															<th
																style="Margin: 0; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0; text-align: left">
																<div class="border-top pv-1"
																	style="border-bottom: 0; border-left: 0; border-right: 0; border-top: 1px solid #ced7e2; padding-bottom: 8px; padding-top: 8px">
																	<span
																		style="display: inline-block; height: 12px; width: 12px; background-color: #007ef2"></span>
																	<span class="regular pl-1"
																		style="font-weight: 400 !important; padding-left: 8px">Estimated
																		Distance</span> <span class="regular"
																		style="float: right; font-weight: 400 !important"><?php echo ($estimatedDistance/1000). "km"?></span>
																</div>
															</th>
														</tr>
													</table>
												</th>
												<th class="pl-2 pr-4 small-6 large-6 columns last"
													style="Margin: 0 auto; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0 auto; padding-left: 16px; padding-right: 32px; text-align: left; width: 292px">
													<table
														style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
														<tr
															style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
															<th
																style="Margin: 0; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0; text-align: left">
																<div class="border-top pv-1"
																	style="border-bottom: 0; border-left: 0; border-right: 0; border-top: 1px solid #ced7e2; padding-bottom: 8px; padding-top: 8px">
																	<span
																		style="display: inline-block; height: 12px; width: 12px; background-color: #007ef2"></span>
																	<span class="regular pl-1"
																		style="font-weight: 400 !important; padding-left: 8px">Actual
																		Distance</span> <span class="regular"
																		style="float: right; font-weight: 400 !important"><?php echo (($estimatedDistance + 50)/1000). "km"?></span>
																</div>
															</th>
														</tr>
													</table>
												</th>
											</tr>
										</tbody>
									</table>
									<table class="row"
										style="border-collapse: collapse; border-spacing: 0; display: table; padding: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; position: relative; text-align: left; vertical-align: top; width: 100%">
										<tbody>
											<tr
												style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
												<th class="pr-2 pl-4 small-6 large-6 columns first"
													style="Margin: 0 auto; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0 auto; padding-left: 32px; padding-right: 16px; text-align: left; width: 292px">
													<table
														style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
														<tr
															style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
															<th
																style="Margin: 0; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0; text-align: left">
																<div class="border-top pv-1"
																	style="border-bottom: 0; border-left: 0; border-right: 0; border-top: 1px solid #ced7e2; padding-bottom: 8px; padding-top: 8px">
																	<span
																		style="display: inline-block; height: 12px; width: 12px; background-color: #9fd1ff"></span>
																	<span class="regular pl-1"
																		style="font-weight: 400 !important; padding-left: 8px">Estimated
																		Time</span> <span class="regular"
																		style="float: right; font-weight: 400 !important"><?php  echo $estimatedTime; ?> mins</span>
																</div>
															</th>
														</tr>
													</table>
												</th>
												<th class="pl-2 pr-4 small-6 large-6 columns last"
													style="Margin: 0 auto; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0 auto; padding-left: 16px; padding-right: 32px; text-align: left; width: 292px">
													<table
														style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
														<tr
															style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
															<th
																style="Margin: 0; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0; text-align: left">
																<div class="border-top pv-1"
																	style="border-bottom: 0; border-left: 0; border-right: 0; border-top: 1px solid #ced7e2; padding-bottom: 8px; padding-top: 8px">
																	<span
																		style="display: inline-block; height: 12px; width: 12px; background-color: #9fd1ff"></span>
																	<span class="regular pl-1"
																		style="font-weight: 400 !important; padding-left: 8px">Actual
																		Time</span> <span class="regular"
																		style="float: right; font-weight: 400 !important"><?php  echo $actualTime ?> mins</span>
																</div>
															</th>
														</tr>
													</table>
												</th>
											</tr>
										</tbody>
									</table>
									<table class="row"
										style="border-collapse: collapse; border-spacing: 0; display: table; padding: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; position: relative; text-align: left; vertical-align: top; width: 100%">
										<tbody>
											<tr
												style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
												<th class="small-1 large-3 columns first"
													style="Margin: 0 auto; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0 auto; text-align: left; width: 142px">
													<table
														style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
														<tr
															style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
															<th
																style="Margin: 0; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0; text-align: left"></th>
														</tr>
													</table>
												</th>
												<th class="small-10 large-6 columns"
													style="Margin: 0 auto; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0 auto; text-align: left; width: 292px">
													<table
														style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
														<tr
															style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
															<th
																style="Margin: 0; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0; text-align: left">
																<h4 class="blue text-center pb-3 pt-2"
																	style="Margin: 0; Margin-bottom: 4px; color: #007ef2; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 18px; font-weight: 700; line-height: 150%; margin: 0; margin-bottom: 4px; padding-bottom: 24px; padding-left: 0; padding-right: 0; padding-top: 16px; text-align: center; word-wrap: normal">PAYABLE
															</h4>
																<div class="border-top pv-1"
																	style="border-bottom: 0; border-left: 0; border-right: 0; border-top: 1px solid #ced7e2; padding-bottom: 8px; padding-top: 8px">
																	<span
																		style="display: inline-block; height: 12px; width: 12px; background-color: #007ef2"></span>
																	<span class="regular pl-1"
																		style="font-weight: 400 !important; padding-left: 8px">Estimated
																		Distance</span> <span class="regular"
																		style="float: right; font-weight: 400 !important"><?php echo ($estimatedDistance/1000). "km"?></span>
																</div>
																<div class="border-top pv-1"
																	style="border-bottom: 0; border-left: 0; border-right: 0; border-top: 1px solid #ced7e2; padding-bottom: 8px; padding-top: 8px">
																	<span
																		style="display: inline-block; height: 12px; width: 12px; background-color: #a0d900"></span>
																	<span class="regular pl-1"
																		style="font-weight: 400 !important; padding-left: 8px">Estimated Time</span> <span class="regular"
																		style="float: right; font-weight: 400 !important"><?php  echo $estimatedTime; ?> mins</span>
																</div>
																<div class="border-top pv-1"
																	style="border-bottom: 0; border-left: 0; border-right: 0; border-top: 1px solid #ced7e2; padding-bottom: 8px; padding-top: 8px">
																	<span
																		style="display: inline-block; height: 12px; width: 12px; background-color: #ffbc10"></span>
																	<span class="regular pl-1"
																		style="font-weight: 400 !important; padding-left: 8px"><strong>Extra Time Cost</strong></span>
																	<span class="regular"
																		style="float: right; font-weight: 400 !important"><?php  echo ($extraTimeUsed == null ? 0 : $this->myCurrency($extraCost)."(".$extraTimeUsed.") mins")?></span>
																</div>
																<div class="border-top pv-1"
																	style="border-bottom: 0; border-left: 0; border-right: 0; border-top: 1px solid #ced7e2; padding-bottom: 8px; padding-top: 8px">
																	<span
																		style="display: inline-block; height: 12px; width: 12px; background-color: #ffbc10"></span>
																	<span class="regular pl-1"
																		style="font-weight: 400 !important; padding-left: 8px"><strong>Amount Payable</strong></span>
																	<span class="regular"
																		style="float: right; font-weight: 400 !important"><?php  echo $this->myCurrency($price)?></span>
																</div>
																<h5 class="text-center pt-3"
																	style="Margin: 0; Margin-bottom: 4px; color: inherit; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; font-weight: 400; line-height: 150%; margin: 0; margin-bottom: 4px; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 24px; text-align: center; word-wrap: normal">
																Total Payable <span class="bold"
																		style="font-weight: 600 !important"><?php  echo $this->myCurrency($price) ?></span> 
																	
																	
																</h5>
																<center class="pv-3" data-parsed=""
																	style="min-width: 276px; padding-bottom: 24px; padding-top: 24px; width: 100%">
																	<table class="button bg-blue float-center"
																		style="Margin: 0 auto; border-collapse: collapse; border-spacing: 0; float: none; margin: 0 auto; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: center; vertical-align: top; width: auto">
																		<tr
																			style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
																			<td
																				style="-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; hyphens: auto; line-height: 150%; margin: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; word-wrap: break-word">
																				<table
																					style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
																					<tr
																						style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
																						<td
																							style="-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; background: #007ef2; border: 2px solid #007ef2; border-collapse: collapse !important; color: #fefefe; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; hyphens: auto; line-height: 150%; margin: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; word-wrap: break-word"><a
																							href="#"
																							style="Margin: 0; border: 0 solid #007ef2; border-radius: 0; color: #fefefe; display: inline-block; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 700; line-height: 120%; margin: 0; padding: 0; padding-bottom: 12px; padding-left: 24px; padding-right: 24px; padding-top: 12px; text-align: left; text-decoration: none">View
																								Full Report</a></td>
																					</tr>
																				</table>
																			</td>
																		</tr>
																	</table>
																</center>
															</th>
														</tr>
													</table>
												</th>
												<th class="small-1 large-3 columns last"
													style="Margin: 0 auto; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0 auto; text-align: left; width: 142px">
													<table
														style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
														<tr
															style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
															<th
																style="Margin: 0; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0; text-align: left"></th>
														</tr>
													</table>
												</th>
											</tr>
										</tbody>
									</table>
								</td>
							</tr>
						</tbody>
					</table>
					<table class="spacer"
						style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
						<tbody>
							<tr
								style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
								<td height="16px"
									style="-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; hyphens: auto; line-height: 16px; margin: 0; mso-line-height-rule: exactly; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; word-wrap: break-word">&#xA0;</td>
							</tr>
						</tbody>
					</table>
					<table bgcolor="#D5F3E9" align="center"
						class="container card card--light-green"
						style="Margin: 0 auto; background: 0 0; border-collapse: collapse; border-spacing: 0; margin: 0 auto; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: inherit; vertical-align: top; width: 600px">
						<tbody>
							<tr
								style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
								<td
									style="-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; background: #d5f3e9 !important; border-collapse: collapse !important; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; hyphens: auto; line-height: 150%; margin: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; word-wrap: break-word">
									<table class="row bg-negotiators"
										style="background: url(https://static.truebill.com/images/email/negotiators.png); background-position: bottom right; background-repeat: no-repeat; background-size: 126px 111px; border-collapse: collapse; border-spacing: 0; display: table; padding: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; position: relative; text-align: left; vertical-align: top; width: 100%">
										<tbody>
											<tr
												style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
												<th class="p-4 small-12 large-12 columns first last"
													style="Margin: 0 auto; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0 auto; padding: 32px; text-align: left; width: 592px">
													<table
														style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
														<tr
															style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
															<th
																style="Margin: 0; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0; text-align: left">
																<table class="row"
																	style="border-collapse: collapse; border-spacing: 0; display: table; padding: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; position: relative; text-align: left; vertical-align: top; width: 100%">
																	<tbody>
																		<tr
																			style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
																			<th class="small-12 large-8 columns first last"
																				style="Margin: 0 auto; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0 auto; padding-left: 0 !important; padding-right: 0 !important; text-align: left; width: 66.66667%">
																				<table
																					style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
																					<tr
																						style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
																						<th
																							style="Margin: 0; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; line-height: 150%; margin: 0; text-align: left">
																							<h3 class="text"
																								style="Margin: 0; Margin-bottom: 4px; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 20px; font-weight: 700; line-height: 150%; margin: 0; margin-bottom: 4px; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; word-wrap: normal">
																								<img class="square-icon"
																									src="https://static.truebill.com/images/email/down-arrow.png"
																									width="16" height="16"
																									style="-ms-interpolation-mode: bicubic; clear: both; display: inline; height: 16px; margin-right: 4px; max-width: 100%; outline: 0; text-decoration: none; width: 16px">Having
																									any problems ? 
																							
																							</h3>
																							<p class="text-light regular"
																								style="Margin: 0; Margin-bottom: 4px; color: #748392; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400 !important; line-height: 150%; margin: 0; margin-bottom: 4px; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left">if
																								you have any problem you can contact our support
																								desk</p>
																							<table class="spacer"
																								style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
																								<tbody>
																									<tr
																										style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
																										<td height="16px"
																											style="-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; hyphens: auto; line-height: 16px; margin: 0; mso-line-height-rule: exactly; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; word-wrap: break-word">&#xA0;</td>
																									</tr>
																								</tbody>
																							</table>
																							<table class="button bg-green"
																								style="Margin: 0; border-collapse: collapse; border-spacing: 0; margin: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: auto">
																								<tr
																									style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
																									<td
																										style="-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; hyphens: auto; line-height: 150%; margin: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; word-wrap: break-word">
																										<table
																											style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
																											<tr
																												style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
																												<td
																													style="-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; background: #00d682; border: 0 solid #00d682; border-collapse: collapse !important; color: #fefefe; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; hyphens: auto; line-height: 150%; margin: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; word-wrap: break-word"><a
																													href="#"
																													style="Margin: 0; border: 0 solid #00d682; border-radius: 0; color: #fefefe; display: inline-block; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 700; line-height: 120%; margin: 0; padding: 0; padding-bottom: 12px; padding-left: 24px; padding-right: 24px; padding-top: 12px; text-align: left; text-decoration: none">Lower
																														my bills</a></td>
																											</tr>
																										</table>
																									</td>
																								</tr>
																							</table>
																						</th>
																					</tr>
																				</table>
																			</th>
																		</tr>
																	</tbody>
																</table>
															</th>
														</tr>
													</table>
												</th>
											</tr>
										</tbody>
									</table>
								</td>
							</tr>
						</tbody>
					</table>
					<table class="spacer"
						style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
						<tbody>
							<tr
								style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
								<td height="16px"
									style="-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 16px; font-weight: 400; hyphens: auto; line-height: 16px; margin: 0; mso-line-height-rule: exactly; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; word-wrap: break-word">&#xA0;</td>
							</tr>
						</tbody>
					</table>
					<table class="spacer"
						style="border-collapse: collapse; border-spacing: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; width: 100%">
						<tbody>
							<tr
								style="padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top">
								<td height="24px"
									style="-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #173049; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 24px; font-weight: 400; hyphens: auto; line-height: 24px; margin: 0; mso-line-height-rule: exactly; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0; text-align: left; vertical-align: top; word-wrap: break-word">&#xA0;</td>
							</tr>
						</tbody>
					</table>
				</center>
			</td>
		</tr>
	</table>
	<div
		style="display: none; white-space: nowrap; font: 15px courier; line-height: 0">&nbsp;
		&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
		&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
		&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</div>
</body>
</html>