<?php
echo $this->headtitle("Booking");
?>
<?php
$flashMessenger = $this->flashMessenger()
	->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
	->setMessageSeparatorString('</li><li>')
	->setMessageCloseString('</li></ul></div>');
?>
<?php echo $flashMessenger->render('error',   array('alert', 'alert-dismissable', 'alert-danger')); ?>
<?php echo $flashMessenger->render('info',    array('alert', 'alert-dismissable', 'alert-info')); ?>
<?php echo $flashMessenger->render('default', array('alert', 'alert-dismissable', 'alert-warning')); ?>
<?php echo $flashMessenger->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>


<section class="page--header">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-6">
				<!-- Page Title Start -->
				<h2 class="page--title h5">Bookings</h2>
				<!-- Page Title End -->

				<ul class="breadcrumb">
					<li class="breadcrumb-item"><a href="ecommerce.html"></a></li>
					<li class="breadcrumb-item active"><span>Customer Bookings</span></li>
				</ul>
			</div>


		</div>
	</div>
</section>


<section id="bookingBoard" class="main--content">
	<div class="panel">
		<!-- Records Header Start -->
		<div class="records--header">
			<div class="title fa-shopping-bag">
				<h3 class="h3">
					All Customer Booking
					<!-- 					 <a href="#" class="btn btn-sm btn-outline-info">Manage -->
					<!-- 						Products</a> -->
				</h3>
				<!-- 				<p>Found Total 1,330 Products</p> -->
			</div>

			<div class="actions">
				<!-- 				<form action="#" class="search flex-wrap flex-md-nowrap"> -->
				<!-- 					<input type="text" class="form-control" placeholder="Product Name..." required> <select name="select" class="form-control"> -->
				<!-- 						<option value="" selected>Product Category</option> -->
				<!-- 					</select> -->
				<!-- 					<button type="submit" class="btn btn-rounded"> -->
				<!-- 						<i class="fa fa-search"></i> -->
				<!-- 					</button> -->
				<!-- 				</form> -->


				<a href="#" class="addProduct btn btn-lg btn-rounded btn-warning">Create
					Booking</a>
			</div>
		</div>
		<!-- Records Header End -->
	</div>
	<div class="row">
		<?php echo $this->partial("booking-menu-list") ?>
		<div class="col-xl-9">
			<div class="panel">
				<div class="panel-heading">
					<h3 class="panel-title">Booking List</h3>


				</div>

				<div class="panel-body">
					<div class="table-responsive">
						<table class="table style--2">
							<thead>
								<tr>

									<th>BOOKING UID</th>
									<th>Customer Name</th>
									<th>Booking Info</th>
									<th>Status</th>
									<th>Amount Paid</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								<!-- Table Row Start -->
								<?php foreach ($allBooking as $booking) : ?>
									<tr>

										<td><?php echo strtoupper($booking["bookingUid"]) ?></td>
										<td><?php echo $booking["user"]["fullName"] ?></td>
										<td><a href="#" class="btn-link"><strong>Booking Class : </strong><?php echo $booking["bookingClass"]["bookingClass"] ?> <br>
										</td>
										<td><?php echo $this->statusHelper($booking["status"]) ?></td>
										<td><?php echo $this->myCurrency($booking["transaction"]['amount']) ?></td>

										<!--                                                 <td><span class="text-muted">#BG6R9853lP</span></td> -->
										<td><a href="<?php echo $this->url("admin/default", ["controller" => "booking", "action" => "view", "id" => $booking["bookingUid"]]) ?>"><i class="fa fa-eye"></i></a> | <a href="#" @click="deleteBooking('<?php echo $booking["id"]?>')"><i class="fa fa-trash"></i></a> </td>
									</tr>
								<?php endforeach; ?>
								<!-- Table Row End -->


							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<script>
	let bookingBoards = new Vue({
		el: "#bookingBoard",
		data() {
			return {
				isDeleting: false
			}
		},
		methods: {
			deleteBooking(id) {

				swal({

					title: "DELETE BOOKING",
					text: "Are you sure you want to remove this booking",
					icon: "warning",
					showCancelButton: true,
					confirmButtonColor: '#3085d6',
					cancelButtonColor: '#d33',
					confirmButtonText: 'REMOVE NOW'
				}).then(function(isConfirm) {

					if (isConfirm) {
						let formData = new FormData();
						formData.append("id", id);
						axios.post("/controller/booking/remove", formData).then(res => {
							if(res.status == 204){
								window.location.reload();
							}
						}).catch(err => {
							swal({
								title: "Error",
								text: err.response.data.messages,
								icon: "error",
								showCancelButton: true,
								confirmButtonColor: '#3085d6',
								cancelButtonColor: '#3085d6',
								confirmButtonText: 'OK'
							})
						});
					}


				});

			},
		},
	});
</script>