<?php
echo $this->headtitle("Upcoming Booking");
?>

<?php
$flashMessenger = $this->flashMessenger()
    ->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');
?>
<?php echo $flashMessenger->render('error',   array('alert', 'alert-dismissable', 'alert-danger')); ?>
<?php echo $flashMessenger->render('info',    array('alert', 'alert-dismissable', 'alert-info')); ?>
<?php echo $flashMessenger->render('default', array('alert', 'alert-dismissable', 'alert-warning')); ?>
<?php echo $flashMessenger->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>


<div id="upcomingbooking">

	<div id="vCenteredModal" class="modal fade">
		<div class="modal-dialog modal-dialog-centered">

			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title">Manage Booking</h5>

					<button type="button" class="close" data-dismiss="modal">&times;</button>
				</div>

				<!-- <div v-if="isWorking">
					<div class="spinner"></div>
				</div> -->
				<div class="modal-body pt-4">

					<select v-if="bookingActions.length" v-model="selectedAction"
						@change="actionLogic($event)" name="select" class="form-control">
						<option v-for="actio in bookingActions" :value="actio.id" selected>{{actio.bookingAction}}</option>
					</select>

					<div v-if="isDispatch">
						<div v-if="bookingdetails.assignedDriver == null">No Driver
							Assigned</div>
						<div v-else>
							<div class="col-md-12">
								<!-- Pricing Item Start -->
								<div class="pricing--item text-center mb-4">
									<hr>
									<h4>Assigned Driver</h4>


									<div class="pricing--features">
										<ul class="list-unstyled">
											<li><strong>
													<th>Driver Name</th>
											</strong> {{bookingdetails.assignedDriver.user.fullName}}</li>
											<li><strong>
													<th>Driver Phone Number</th>
											</strong> {{bookingdetails.assignedDriver.user.phoneNumber}}</li>
											<!-- <li><strong>Unlimited</strong> integer felis odio</li> -->
										</ul>
									</div>
									<div v-if="isChangeDriverTrigger">
										<div class="form-group">
											<label> <span class="label-text">Available Drivers</span> <select
												v-if="inactiveDivers.length" @change="onChangeDriver()"
												v-model="selectDriver" name="select" class="form-control">
													<option v-for="driver in inactiveDivers" :value="driver.id">{{driver.user.fullName}}</option>

											</select>
											</label>
										</div>

										<button type="button" v-if="showAssignButton"
											:disabled="isAssigningDriver" @click="reAssignDriver()"
											class="btn btn-sm btn-block btn-rounded btn-success">
											<div v-if="isAssigningDriver">Processing...</div>
											<div v-else>Re-Assign Driver</div>
										</button>
									</div>
									<div v-else class="pricing--action">
										<a href="" @click="dispatchDriver()"
											:disabled="isProcessingDispatch"
											class="btn btn-rounded btn-success">
											<div v-if="isProcessingDispatch">Processing...</div>
											<div v-else>Dispatch Driver</div>
										</a>
									</div>
								</div>
								<!-- Pricing Item End -->
							</div>
						</div>
					</div>
					<div v-if="isReassign">
						<div v-if="bookingdetails.assignedDriver == null">
							<hr>

							<div v-if="isShowAssignForm">
								<div class="form-group">
									<label> <span class="label-text">Available Drivers</span> <select
										v-if="inactiveDivers.length" @change="onChangeDriver()"
										v-model="selectDriver" name="select" class="form-control">
											<option v-for="driver in inactiveDivers" :value="driver.id">{{driver.user.fullName}}</option>

									</select>
									</label>
								</div>


								<button type="button" v-if="showAssignButton"
									:disabled="isAssigningDriver" @click="assignDriver()"
									class="btn btn-sm btn-block btn-rounded btn-success">
									<div v-if="isAssigningDriver">Processing...</div>
									<div v-else>Assign Driver</div>
								</button>
							</div>
							<button v-else @click="showAssignForm()"
								class="btn btn-outline-success btn-block">Assign A Driver</button>
						</div>
						<div v-else>


							<div class="col-md-12">
								<!-- Pricing Item Start -->
								<div class="pricing--item text-center mb-4">
									<hr>
									<h4>Assigned Driver</h4>


									<div class="pricing--features">
										<ul class="list-unstyled">
											<li><strong>
													<th>Driver Name</th>
											</strong> {{bookingdetails.assignedDriver.user.fullName}}</li>
											<li><strong>
													<th>Driver Phone Number</th>
											</strong> {{bookingdetails.assignedDriver.user.phoneNumber}}</li>
											<!-- <li><strong>Unlimited</strong> integer felis odio</li> -->
										</ul>
									</div>
									<div v-if="isChangeDriverTrigger">
										<div class="form-group">
											<label> <span class="label-text">Available Drivers</span> <select
												v-if="inactiveDivers.length" @change="onChangeDriver()"
												v-model="selectDriver" name="select" class="form-control">
													<option v-for="driver in inactiveDivers" :value="driver.id">{{driver.user.fullName}}</option>

											</select>
											</label>
										</div>

										<button type="button" v-if="showAssignButton"
											:disabled="isAssigningDriver" @click="reAssignDriver()"
											class="btn btn-sm btn-block btn-rounded btn-success">
											<div v-if="isAssigningDriver">Processing...</div>
											<div v-else>Re-Assign Driver</div>
										</button>
									</div>
									<div v-else class="pricing--action">
										<a href="#" @click="triggerChangeDriver()"
											class="btn btn-rounded btn-success">Change Driver</a>
									</div>
								</div>
								<!-- Pricing Item End -->
							</div>

						</div>
					</div>



					<!-- <div class="form-group">
						<label> <span class="label-text">Driver Full Name</span> <input type="text" ref="fullname" class="form-control">
						</label>
					</div> -->


					<!-- <button disabled="submitStatus" type="button" value="Submit" class="btn btn-lg btn-block btn-rounded btn-success">Register Now</button> -->

				</div>
			</div>

		</div>
	</div>
	<section class="page--header">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-6">
					<!-- Page Title Start -->
					<h2 class="page--title h5">Bookings</h2>
					<!-- Page Title End -->

					<ul class="breadcrumb">
						<li class="breadcrumb-item"><a href=""></a></li>
						<li class="breadcrumb-item active"><span>Products</span></li>
					</ul>
				</div>


			</div>
		</div>
	</section>


	<section class="main--content">
		<div class="panel">
			<!-- Records Header Start -->
			<div class="records--header">
				<div class="title fa-shopping-bag">
					<h3 class="h3">
						Upcoming Booking
						<!-- 					 <a href="#" class="btn btn-sm btn-outline-info">Manage -->
						<!-- 						Products</a> -->
					</h3>
					<!-- 				<p>Found Total 1,330 Products</p> -->
				</div>

				<div class="actions">
					<form action="#" class="search flex-wrap flex-md-nowrap">
						<input type="text" class="form-control"
							placeholder="Product Name..." required> <select name="select"
							class="form-control">
							<option value="" selected>Product Category</option>
						</select>
						<button type="submit" class="btn btn-rounded">
							<i class="fa fa-search"></i>
						</button>
					</form>



				</div>
			</div>
			<!-- Records Header End -->
		</div>
		<div class="row">
			<?php echo $this->partial("booking-menu-list") ?>
			<div class="col-xl-9">
				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">Booking List</h3>


					</div>

					<div class="panel-body">
						<div class="table-responsive">
							<table class="table style--2">
								<thead>
									<tr>

										<th>BOOKING UID</th>
										<th>Customer Name</th>
										<th>Booking Info</th>
										<th>Status</th>
										<th>Amount Paid</th>
										<th>Action</th>
									</tr>
								</thead>
								<tbody>
									<!-- Table Row Start -->
									<?php foreach ($allBooking as $booking) : ?>
										<tr>

										<td><?php echo strtoupper($booking["bookingUid"]) ?></td>
										<td><?php echo $booking["user"]["fullName"] ?></td>
										<td><a href="#" class="btn-link"><strong>Booking Class : </strong><?php echo $booking["bookingClass"]["bookingClass"] ?> <br></td>
										<td><?php echo $this->statusHelper($booking["status"]) ?><br>
											<strong>Pick Up Time :</strong> <?php echo $this->dateformat($booking["pickupDate"], IntlDateFormatter::MEDIUM, IntlDateFormatter::MEDIUM) ?></td>
										<td><?php echo $this->myCurrency($booking["transaction"]['amount']) ?></td>

										<!--                                                 <td><span class="text-muted">#BG6R9853lP</span></td> -->
										<td><a
											href="<?php echo $this->url("admin/default", ["controller" => "booking", "action" => "view", "id" => $booking["bookingUid"]]) ?>"><i
												class="fa fa-eye"></i></a> | <a href="#vCenteredModal"
											@click="viewBooking('<?php echo $booking["bookingUid"] ?>')"
											data-toggle="modal"><i class="fa fa-wrench"></i></a></td>
									</tr>
									<?php endforeach; ?>
									<!-- Table Row End -->


								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>
<script>
	let upcomingbooking = new Vue({
		el: "#upcomingbooking",
		data() {
			return {
				isWorking: false,
				bookingdetails: {},
				bookingActions: [],
				selectedAction: "",

				// action logic
				isDispatch: false,
				isProcessingDispatch: false,
				isReassign: false,
				isAssign: false,

				isChangeDriverTrigger: false,
				inactiveDivers: [],
				showAssignButton: false,
				isShowAssignForm: false,
				isAssigningDriver: false,
				selectDriver: '',

			}
		},
		mounted() {
			this.getBookingActions();
		},
		methods: {


			viewBooking(id) {
				// this.isWorking = true;
				axios.get("/customer/getbookingdetails/" + id).then(res => {
					if (res.status == 200) {
						this.isWorking = false;
						this.bookingdetails = res.data.data;
					}
				}).catch();
			},

			getBookingActions() {
				axios.get("/customer/getBookingActions").then(res => {
					if (res.status == 200) {
						this.bookingActions = res.data.data;
					}

				}).catch();
			},

			resetActions() {
				this.isAssign = false;
				this.isDispatch = false;
				this.isReassign = false;
			},

			getAllAinactiveDrivers() {
				axios.get("/controller/driver/inactivedriver").then(res => {
					if (res.status == 200) {
						this.inactiveDivers = res.data.drivers
					}
				});
			},


			// Begin dispatch 
			dispatchDriver() {
				this.isProcessingDispatch = true;
				let formData = new FormData();
				formData.append("bookingId", this.bookingdetails.id);
				axios.post("/controller/driver/dispatch", formData).then(res => {
					if (res.status == 201) {
						this.isProcessingDispatch = false;
						window.location.reload();
					}
				}).catch();
			},
			// end dispatch


			triggerChangeDriver() {
				// show reaasinged select form 
				this.isChangeDriverTrigger = true;
				this.getAllAinactiveDrivers();
			},

			onChangeDriver() {
				if (this.selectDriver != "") {
					this.showAssignButton = true;
				}
			},

			reAssignDriver() {
				this.isAssigningDriver = true;
				let formData = new FormData();
				formData.append("driver", this.selectDriver);
				formData.append("bookingId", this.bookingdetails.id);
				axios.post('/controller/driver/reassigndriver', formData).then(res => {
					if (res.status == 201) {
						window.location.reload();
					}
				}).catch(err=>{
					this.isAssigningDriver = false;
				});
			},
			showAssignForm() {
				this.isShowAssignForm = true;
				this.getAllAinactiveDrivers();
			},

			assignDriver() {

				this.isAssigningDriver = true;
				let formData = new FormData();
				formData.append("driver", this.selectDriver);
				formData.append("bookingId", this.bookingdetails.id);
				axios.post('/controller/driver/assigndriver', formData).then(res => {
					if (res.status == 201) {
						window.location.reload();
					}
				}).catch(err=>{
					this.isAssigningDriver = false;
				});
			},

			actionLogic(event) {
				let actionId = event.target.value;
				this.resetActions();
				if (actionId == 10) {

					this.isDispatch = true;
				} else if (actionId == 20) {

					this.isReassign = true;
				} else if (actionId == 30) {
					this.isAssign = true;
				}
			}
		},


	});
</script>