<?php

?>

<div class="col-lg-4">
                <!-- Panel Start -->
                <div class="panel">
                    <div class="panel-heading">
                        <h3 class="panel-title">Customer Details</h3>
                    </div>

                    <div class="panel-content panel-about">
                      
                        <table>
                            <tr>
                                <th><i class="fas fa-user"></i>Name</th>
                                <td><?php  echo $user->getFullName() ?></td>
                            </tr>
                            <tr>
                                <th><i class="fas fa-phone"></i>Phone</th>
                                <td><?php  echo $user->getPhoneNumber()?></td>
                            </tr>
                            <tr>
                                <th><i class="fas fa-email"></i>Email</th>
                                <td><?php echo $user->getEmail() ?></td>
                            </tr>
                            <tr>
                                <th><i class="fas fa-mobile-alt"></i>Role</th>
                                <td><?php  echo $user->getRole()->getName()?></td>
                            </tr>
                            <tr>
                                <th><i class="fas fa-globe"></i>State</th>
                                <td><?php  echo $user->getState()->getState() ?></td>
                            </tr>
                            
                            <tr>
                                <th><i class="fas fa-globe"></i>Registered</th>
                                <td><?php  echo $this->dateFormat($user->getRegistrationDate(), IntlDateFormatter::MEDIUM, IntlDateFormatter::SHORT) ?></td>
                            </tr>
                            
                            <tr>
                                <th><i class="fas fa-globe"></i>Updated  </th>
                                <td><?php  echo $this->dateFormat($user->getUpdatedOn(), IntlDateFormatter::MEDIUM, IntlDateFormatter::SHORT) ?></td>
                            </tr>
                        </table>
                    </div>

                    
                </div>
                <!-- Panel End -->

               

               

                <!-- Panel Start -->
                <div class="panel">
                    <div class="panel-heading">
                        <h3 class="panel-title">To-Do List</h3>

                        <div class="dropdown">
                            <button type="button" class="btn-link dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-ellipsis-v"></i>
                            </button>

                            <ul class="dropdown-menu">
                                <li><a href="#"><i class="fa fa-sync"></i>Update Data</a></li>
                                <li><a href="#"><i class="fa fa-times"></i>Remove Panel</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="todo--panel">
                        <!-- <form action="#">
                            <ul class="list-group" data-trigger="scrollbar">
                                <li class="list-group-item">
                                    <label class="todo--label">
                                        <input type="checkbox" name="checkbox" value="1" class="todo--input" checked>
                                        <span class="todo--text">Schedule Meeting</span>
                                    </label>

                                    <a href="#" class="todo--remove">&times;</a>
                                </li>
                                <li class="list-group-item">
                                    <label class="todo--label">
                                        <input type="checkbox" name="checkbox" value="2" class="todo--input">
                                        <span class="todo--text">Call Clients To Follow-Up</span>
                                    </label>

                                    <a href="#" class="todo--remove">&times;</a>
                                </li>
                                <li class="list-group-item">
                                    <label class="todo--label">
                                        <input type="checkbox" name="checkbox" value="3" class="todo--input" checked>
                                        <span class="todo--text">Book Flight For Holiday</span>
                                    </label>

                                    <a href="#" class="todo--remove">&times;</a>
                                </li>
                                <li class="list-group-item">
                                    <label class="todo--label">
                                        <input type="checkbox" name="checkbox" value="4" class="todo--input">
                                        <span class="todo--text">Forward Important Tasks</span>
                                    </label>

                                    <a href="#" class="todo--remove">&times;</a>
                                </li>
                                <li class="list-group-item">
                                    <label class="todo--label">
                                        <input type="checkbox" name="checkbox" value="6" class="todo--input">
                                        <span class="todo--text">Important Tasks</span>
                                    </label>

                                    <a href="#" class="todo--remove">&times;</a>
                                </li>
                            </ul>

                            <div class="input-group">
                                <input type="text" name="todo" placeholder="Add New Task" class="form-control" autocomplete="off" required>

                                <div class="input-group-btn">
                                    <button type="submit" class="btn-link">+</button>
                                </div>
                            </div>
                        </form> -->
                    </div>
                </div>
                <!-- Panel End -->

                <!-- Panel Start -->
                <div class="panel">
                    <div class="panel-heading">
                        <h3 class="panel-title">Feeds &amp; Activities</h3>

                        <!-- <div class="dropdown">
                            <button type="button" class="btn-link dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-ellipsis-v"></i>
                            </button>

                            <ul class="dropdown-menu">
                                <li><a href="#"><i class="fa fa-sync"></i>Update Data</a></li>
                                <li><a href="#"><i class="fa fa-times"></i>Remove Panel</a></li>
                            </ul>
                        </div> -->
                    </div>

                    <div class="feeds-panel">
                        <!-- <ul class="nav">
                            <li>
                                <span class="time">2 mins</span>
                                <i class="fa fa-shopping-cart text-white bg-blue"></i>
                                <span class="text">New Order Received</span>
                            </li>
                            <li>
                                <span class="time">10 mins</span>
                                <i class="fa fa-user text-white bg-orange"></i>
                                <span class="text">Updated Profile Picture</span>
                            </li>
                            <li>
                                <span class="time">20 mins</span>
                                <i class="fa fa-comment text-white bg-red"></i>
                                <span class="text"><a href="#">John Doe</a> Commented on <a href="#">News #123</a></span>
                            </li>
                            <li>
                                <span class="time">21 mins</span>
                                <i class="fa fa-shopping-cart text-white bg-blue"></i>
                                <span class="text">New Order Received</span>
                            </li>
                            <li>
                                <span class="time">25 mins</span>
                                <i class="fa fa-user text-white bg-green"></i>
                                <span class="text">New User Registered</span>
                            </li>
                            <li>
                                <span class="time">25 mins</span>
                                <i class="fa fa-times text-white bg-dark"></i>
                                <span class="text">Order <a href="#">#24DP01</a> Rejected</span>
                            </li>
                            <li>
                                <span class="time">2 hours</span>
                                <i class="fa fa-comment text-white bg-red"></i>
                                <span class="text"><a href="#">John Doe</a> Commented on <a href="#">News #123</a></span>
                            </li>
                            <li>
                                <span class="time">3 hours</span>
                                <i class="fa fa-user text-white bg-orange"></i>
                                <span class="text">You Uploaded A Image</span>
                            </li>
                            <li>
                                <span class="time">4 hours</span>
                                <i class="fa fa-shopping-cart text-white bg-blue"></i>
                                <span class="text">New Order Received</span>
                            </li>
                            <li>
                                <span class="time">8 hours</span>
                                <i class="fa fa-user text-white bg-green"></i>
                                <span class="text">New User Registered</span>
                            </li>
                            <li>
                                <span class="time">22 hours</span>
                                <i class="fa fa-shopping-cart text-white bg-blue"></i>
                                <span class="text">New Order Received</span>
                            </li>
                        </ul> -->
                    </div>
                </div>
                <!-- Panel End -->
            </div>