<div id="board" v-cloak>
	<section class="page--header">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-6">
					<!-- Page Title Start -->
					<h2 class="page--title h5">Dashboard</h2>
					<!-- Page Title End -->

					<ul class="breadcrumb">
						<li class="breadcrumb-item active"><span>Dashboard</span></li>
					</ul>
				</div>


			</div>
		</div>
	</section>
	<section class="main--content">
		<div class="row gutter-20">
			<div class="col-md-4">
				<div class="panel">
					<!-- Mini Stats Panel Start -->
					<div class="miniStats--panel">
						<div class="miniStats--header bg-darker">
							<!-- 								<p class="miniStats--chart" data-trigger="sparkline" -->
							<!-- 									data-type="bar" data-width="4" data-height="30" -->
							<!-- 									data-color="#2bb3c0">5,6,9,4,9,5,3,5,9,15,3,2,2,3,9,11,9,7,20,9,7,6</p> -->

							<p class="miniStats--label text-white bg-blue">
								<!-- 									<i class="fa fa-level-up-alt"></i> <span>10%</span> -->
							</p>
						</div>

						<div class="miniStats--body">
							<i class="miniStats--icon fa fa-user text-blue"></i>

							<!-- 								<p class="miniStats--caption text-blue">Monthly</p> -->
							<h3 class="miniStats--title h4">TOTAL CUSTOMERS</h3>
							<p class="miniStats--num text-blue">{{customers}}</p>
						</div>
					</div>
					<!-- Mini Stats Panel End -->
				</div>
			</div>

			<div class="col-md-4">
				<div class="panel">
					<!-- Mini Stats Panel Start -->
					<div class="miniStats--panel">
						<div class="miniStats--header bg-darker">
							<!-- 								<p class="miniStats--chart" data-trigger="sparkline" -->
							<!-- 									data-type="bar" data-width="4" data-height="30" -->
							<!-- 									data-color="#e16123">2,2,3,9,11,9,7,20,9,7,6,5,6,9,4,9,5,3,5,9,15,3</p> -->

							<p class="miniStats--label text-white bg-orange">
								<!-- 									<i class="fa fa-level-down-alt"></i> <span>10%</span> -->
							</p>
						</div>

						<div class="miniStats--body">
							<i class="miniStats--icon fa fa-ticket-alt text-orange"></i>

							<!-- 								<p class="miniStats--caption text-orange">Monthly</p> -->
							<h3 class="miniStats--title h4">INITIATED BOOKING</h3>
							<p class="miniStats--num text-orange">{{initiatedBooking}}</p>
						</div>
					</div>
					<!-- Mini Stats Panel End -->
				</div>
			</div>

			<div class="col-md-4">
				<div class="panel">
					<!-- Mini Stats Panel Start -->
					<div class="miniStats--panel">
						<div class="miniStats--header bg-darker">
							<!-- 								<p class="miniStats--chart" data-trigger="sparkline" -->
							<!-- 									data-type="bar" data-width="4" data-height="30" -->
							<!-- 									data-color="#009378">2,2,3,9,11,9,7,20,9,7,6,5,6,9,4,9,5,3,5,9,15,3</p> -->

							<p class="miniStats--label text-white bg-green">
								<!-- 									<i class="fa fa-level-up-alt"></i> <span>10%</span> -->
							</p>
						</div>

						<div class="miniStats--body">
							<i class="miniStats--icon fa fa-rocket text-green"></i>

							<!-- 								<p class="miniStats--caption text-green">Monthly</p> -->
							<h3 class="miniStats--title h4">ACTIVE TRIP</h3>
							<p class="miniStats--num text-green">{{activeTrip}}</p>
						</div>
					</div>
					<!-- Mini Stats Panel End -->
				</div>
			</div>

			<!-- 			<div class="col-xl-8 col-md-6"> -->
			<!-- 				<div class="panel"> -->
			<!-- 					<div class="panel-heading"> -->
			<!-- 						<h3 class="panel-title">Yearly Earning Graph Overview</h3> -->

			<!-- 						<div class="dropdown"> -->
			<!-- 							<button type="button" class="btn-link dropdown-toggle" data-toggle="dropdown"> -->
			<!-- 								<i class="fa fa-ellipsis-v"></i> -->
			<!-- 							</button> -->

			<!-- 							<ul class="dropdown-menu"> -->
			<!-- 								<li><a href="#"><i class="fa fa-sync"></i>Update Data</a></li> -->
			<!-- 								<li><a href="#"><i class="fa fa-cogs"></i>Settings</a></li> -->
			<!-- 								<li><a href="#"><i class="fa fa-times"></i>Remove Panel</a></li> -->
			<!-- 							</ul> -->
			<!-- 						</div> -->
			<!-- 					</div> -->

			<!-- 					<div class="panel-chart"> -->
			<!-- Morris Area Chart 01 Start -->
			<!-- 						<div id="morrisAreaChart01" class="chart--body area--chart style--1"></div> -->
			<!-- Morris Area Chart 01 End -->

			<!-- 						<div class="chart--stats style--1"> -->
			<!-- 							<ul class="nav"> -->
			<!-- 								<li data-overlay="1 orange"> -->
			<!-- 									<p class="amount">$10,320,340</p> -->
			<!-- 									<p> -->
			<!-- 										<span class="label">Order</span> <span class="text-red"><i class="fa fa-long-arrow-alt-down"></i>2.25%</span> -->
			<!-- 									</p> -->
			<!-- 								</li> -->
			<!-- 								<li data-overlay="1 red"> -->
			<!-- 									<p class="amount">$235,090</p> -->
			<!-- 									<p> -->
			<!-- 										<span class="label">Shipment</span> <span class="text-green"><i class="fa fa-long-arrow-alt-up"></i>2.25%</span> -->
			<!-- 									</p> -->
			<!-- 								</li> -->
			<!-- 								<li data-overlay="1 blue"> -->
			<!-- 									<p class="amount">$134,900</p> -->
			<!-- 									<p> -->
			<!-- 										<span class="label">Tax</span> <span class="text-red"><i class="fa fa-long-arrow-alt-down"></i>2.25%</span> -->
			<!-- 									</p> -->
			<!-- 								</li> -->
			<!-- 								<li data-overlay="1 green"> -->
			<!-- 									<p class="amount">$1,340</p> -->
			<!-- 									<p> -->
			<!-- 										<span class="label">Revenue</span> <span class="text-green"><i class="fa fa-long-arrow-alt-up"></i>2.25%</span> -->
			<!-- 									</p> -->
			<!-- 								</li> -->
			<!-- 							</ul> -->
			<!-- 						</div> -->
			<!-- 					</div> -->
			<!-- 				</div> -->
			<!-- 			</div> -->

			<!-- 			<div class="col-xl-4 col-md-6"> -->
			<!-- 				<div class="panel"> -->
			<!-- 					<div class="panel-heading"> -->
			<!-- 						<h3 class="panel-title">Market Trends</h3> -->

			<!-- 						<div class="dropdown"> -->
			<!-- 							<button type="button" class="btn-link dropdown-toggle" data-toggle="dropdown"> -->
			<!-- 								<i class="fa fa-ellipsis-v"></i> -->
			<!-- 							</button> -->

			<!-- 							<ul class="dropdown-menu"> -->
			<!-- 								<li><a href="#">This Week</a></li> -->
			<!-- 								<li><a href="#">Last Week</a></li> -->
			<!-- 							</ul> -->
			<!-- 						</div> -->
			<!-- 					</div> -->

			<!-- 					<div class="panel-chart"> -->
			<!-- Morris Area Chart 02 Start -->
			<!-- 						<div id="morrisAreaChart02" class="chart--body area--chart style--1"></div> -->
			<!-- Morris Area Chart 02 End -->

			<!-- 						<div class="chart--stats style--2"> -->
			<!-- 							<ul class="nav"> -->
			<!-- 								<li> -->
			<!-- 									<p class="amount">$56,700</p> -->
			<!-- 									<p data-overlay="1 blue"> -->
			<!-- 										<span class="label">TOTAL EQUITY</span> -->
			<!-- 									</p> -->
			<!-- 								</li> -->
			<!-- 								<li> -->
			<!-- 									<p class="amount">$4,000</p> -->
			<!-- 									<p data-overlay="1 red"> -->
			<!-- 										<span class="label">TOTAL DEBT</span> -->
			<!-- 									</p> -->
			<!-- 								</li> -->
			<!-- 							</ul> -->
			<!-- 						</div> -->
			<!-- 					</div> -->
			<!-- 				</div> -->
			<!-- 			</div> -->



			<div class="col-xl-9">
				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">INITIATED BOOKING</h3>

						<div class="dropdown">
							<button type="button" class="btn-link dropdown-toggle" data-toggle="dropdown">
								<i class="fa fa-ellipsis-v"></i>
							</button>


						</div>
					</div>

					<div class="panel-body">
						<div class="table-responsive">
							<table class="table style--2">
								<thead>
									<tr>
										<th>TRACKING ID</th>
										<th>PICKUP TIME</th>
										<!-- <th>AMOUNT PAID</th> -->
										<th>BOOKING CLASS</th>
										<th>BOOKING TYPE</th>
										<th>ACTION</th>
										<th>E/PRICE</th>
									</tr>
								</thead>
								<tbody>
									<!-- Table Row Start -->
									<tr v-for="data in splashInitiatedBooking ">
										<!-- <td><img src="assets/img/products/thumb-01.jpg" alt=""></td> -->
										<td>{{data.bookingUid.toUpperCase()}}</td>
										<td><a href="#" class="btn-link">{{formatPHPDate(data.pickupDate.date)}}
											</a></td>
										<td>{{data.bookingClass.bookingClass}}</td>
										<!-- <td>{{data.bookingType.bookingType}}</td> -->
										<td><span class="label label-success">{{data.status.status}}</span></td>
										<td><a :href="initiateBookingListLink(data.bookingUid)"><i class="fa fa-eye"></i></a></td>
										<td>
											<div v-if="data.bookingsEstimatedPrice == null"><a :disabled="isNotifyingCustomer" class="btn btn-success" @click="notifyCustomer(data.id)"><span v-if="isNotifyingCustomer"> ...Processing</span><span v-else class="label label-success">Notify Rider of Cost</span></a></div>
											<div v-else>&#8358;{{formatPrice(data.bookingsEstimatedPrice)}}</div>
										</td>
									</tr>
									<!-- Table Row End -->


								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>

			<div class="col-xl-3">
				<div class="panel">
					<div class="panel-heading">
						<!-- <h3 class="panel-title">To-Do List</h3> -->

						<div class="dropdown">
							<button type="button" class="btn-link dropdown-toggle" data-toggle="dropdown">
								<i class="fa fa-ellipsis-v"></i>
							</button>

							<ul class="dropdown-menu">
								<!-- <li><a href="#"><i class="fa fa-sync"></i>Update Data</a></li>
								<li><a href="#"><i class="fa fa-times"></i>Remove Panel</a></li> -->
							</ul>
						</div>
					</div>

					<div class="todo--panel">
						<!-- <form action="#">
							<ul class="list-group" data-trigger="scrollbar">
								<li class="list-group-item"><label class="todo--label"> <input type="checkbox" name="todo_id" value="1" class="todo--input" checked> <span class="todo--text">Schedule Meeting</span>
									</label> <a href="#" class="todo--remove">&times;</a></li>
								<li class="list-group-item"><label class="todo--label"> <input type="checkbox" name="todo_id" value="2" class="todo--input">
										<span class="todo--text">Call Clients To Follow-Up</span>
									</label> <a href="#" class="todo--remove">&times;</a></li>
								<li class="list-group-item"><label class="todo--label"> <input type="checkbox" name="todo_id" value="3" class="todo--input" checked> <span class="todo--text">Book Flight For Holiday</span>
									</label> <a href="#" class="todo--remove">&times;</a></li>
								<li class="list-group-item"><label class="todo--label"> <input type="checkbox" name="todo_id" value="4" class="todo--input">
										<span class="todo--text">Forward Important Tasks</span>
									</label> <a href="#" class="todo--remove">&times;</a></li>
								<li class="list-group-item"><label class="todo--label"> <input type="checkbox" name="todo_id" value="6" class="todo--input">
										<span class="todo--text">Important Tasks</span>
									</label> <a href="#" class="todo--remove">&times;</a></li>
							</ul>

							<div class="input-group">
								<input type="text" name="todo" placeholder="Add New Task" class="form-control" autocomplete="off" required>

								<div class="input-group-btn">
									<button type="submit" class="btn-link">+</button>
								</div>
							</div>
						</form> -->
					</div>
				</div>
			</div>

			<div class="col-xl-9">
				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">IN TRANSIT</h3>

						<div class="dropdown">
							<button type="button" class="btn-link dropdown-toggle" data-toggle="dropdown">
								<i class="fa fa-ellipsis-v"></i>
							</button>


						</div>
					</div>

					<div class="panel-body">
						<div class="table-responsive">
							<table class="table style--2">
								<thead>
									<tr>
										<th>BOOKING ID</th>
										<th>ACTIVE PERIOD</th>
										<!-- <th>AMOUNT PAID</th> -->
										<th>PICK UP TIME</th>
										<th>ACTIVE TRIP</th>
										<th>STATUS</th>
										<th>ACTION</th>
									</tr>
								</thead>
								<tbody v-if="splashInTransitBooking.length">
									<!-- Table Row Start -->
									<tr v-for="data in splashInTransitBooking">
										<!-- <td><img src="assets/img/products/thumb-01.jpg" alt=""></td> -->
										<td>{{data.bookingUid.toUpperCase()}}</td>
										<!-- <td><a href="#" class="btn-link">{{formatPHPDate(data.startTime.date)}}
												- {{formatPHPDate(data.endTime.date)}}</a></td> -->
										<td>{{data.bookingClass.bookingClass}}</td>
										<td>{{formatPHPDate(data.trip.started.date)}}</td>
										<td><span class="label label-success">{{data.status.status}}</span></td>
										<td><a :href="initiateBookingListLink(data.bookingUid)"><i class="fa fa-eye"></i></a></td>
									</tr>
									<!-- Table Row End -->


								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>

			<div class="col-xl-3 col-md-6">
				<div class="panel">
					<div class="panel-heading">
						<!-- <h3 class="panel-title">Total Overdue</h3> -->

						<div class="dropdown">
							<button type="button" class="btn-link dropdown-toggle" data-toggle="dropdown">
								<i class="fa fa-ellipsis-v"></i>
							</button>

							<!-- <ul class="dropdown-menu">
								<li><a href="#"><i class="fa fa-sync"></i>Update Data</a></li>
								<li><a href="#"><i class="fa fa-cogs"></i>Settings</a></li>
								<li><a href="#"><i class="fa fa-times"></i>Remove Panel</a></li>
							</ul> -->
						</div>
					</div>

					<div class="panel-chart">
						<div class="chart--title text-blue">
							<!-- <h2 class="h2">$14,200,000</h2> -->
						</div>

						<!-- Morris Line Chart 03 Start -->
						<!-- <div id="morrisLineChart03" class="chart--body line--chart style--3"></div> -->
						<!-- Morris Line Chart 03 End -->

						<!-- <div class="chart--action">
							<a href="#" class="btn-link">Export PDF <i class="fa fa-long-arrow-right"></i></a>
						</div> -->
					</div>
				</div>
			</div>



			<div class="col-xl-9">
				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">COMPLETED BOOKING</h3>

						<div class="dropdown">
							<button type="button" class="btn-link dropdown-toggle" data-toggle="dropdown">
								<i class="fa fa-ellipsis-v"></i>
							</button>


						</div>
					</div>

					<div class="panel-body">
						<div class="table-responsive">
							<table class="table style--2">
								<thead>
									<tr>
										<th>TRACKING ID</th>
										<th>USER DETAILS</th>


										<th>TRIP DETAILs</th>

										<th>STATUS</th>
										<th>ACTION</th>
									</tr>
								</thead>
								<tbody v-if="splashCompletedTrip.length">
									<!-- Table Row Start -->
									<tr v-for="data in splashCompletedTrip">

										<td>{{data.bookingUid.toUpperCase()}}</td>
										<td><strong>{{data.user.fullName}} ({{data.user.userUid}})</strong><br></td>


										<td><a href="#" class="btn-link">Trip Started :{{formatPHPDate(data.trip.started.date)}}
											</a><br>
											Trip Ended :{{formatPHPDate(data.trip.ended.date)}}
										</td>

										<td><span class="label label-success">{{data.status.status}}</span></td>
										<td><a :href="initiateBookingListLink(data.bookingUid)"><i class="fa fa-eye"></i></a></td>
									</tr>
									<!-- Table Row End -->


								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>

			<div class="col-xl-3 col-md-6">
				<div class="panel">
					<div class="panel-heading">
						<!-- <h3 class="panel-title">Total Overdue</h3> -->

						<div class="dropdown">
							<button type="button" class="btn-link dropdown-toggle" data-toggle="dropdown">
								<i class="fa fa-ellipsis-v"></i>
							</button>

							<!-- <ul class="dropdown-menu">
								<li><a href="#"><i class="fa fa-sync"></i>Update Data</a></li>
								<li><a href="#"><i class="fa fa-cogs"></i>Settings</a></li>
								<li><a href="#"><i class="fa fa-times"></i>Remove Panel</a></li>
							</ul> -->
						</div>
					</div>

					<div class="panel-chart">
						<div class="chart--title text-blue">
							<!-- <h2 class="h2">$14,200,000</h2> -->
						</div>

						<!-- Morris Line Chart 03 Start -->
						<!-- <div id="morrisLineChart03" class="chart--body line--chart style--3"></div> -->
						<!-- Morris Line Chart 03 End -->

						<div class="chart--action">
							<!-- <a href="#" class="btn-link">Export PDF <i class="fa fa-long-arrow-right"></i></a> -->
						</div>
					</div>
				</div>
			</div>






			<div class="col-xl-6 col-md-6">
				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">Feed back</h3>


					</div>

					<div class="feeds-panel">
						<ul class="nav">
							<!-- <li><span class="time">2 mins</span> <i class="fa fa-shopping-cart text-white bg-blue"></i> <span class="text">New Order Received</span></li>
							<li><span class="time">10 mins</span> <i class="fa fa-user text-white bg-orange"></i> <span class="text">Updated
									Profile Picture</span></li>
							<li><span class="time">20 mins</span> <i class="fa fa-comment text-white bg-red"></i> <span class="text"><a href="#">John Doe</a> Commented on <a href="#">News #123</a></span>
							</li>
							<li><span class="time">21 mins</span> <i class="fa fa-shopping-cart text-white bg-blue"></i> <span class="text">New Order Received</span></li>
							<li><span class="time">25 mins</span> <i class="fa fa-user text-white bg-green"></i> <span class="text">New
									User Registered</span></li>
							<li><span class="time">25 mins</span> <i class="fa fa-times text-white bg-dark"></i> <span class="text">Order
									<a href="#">#24DP01</a> Rejected
								</span></li>
							<li><span class="time">2 hours</span> <i class="fa fa-comment text-white bg-red"></i> <span class="text"><a href="#">John Doe</a> Commented on <a href="#">News #123</a></span>
							</li>
							<li><span class="time">3 hours</span> <i class="fa fa-user text-white bg-orange"></i> <span class="text">You
									Uploaded A Image</span></li>
							<li><span class="time">4 hours</span> <i class="fa fa-shopping-cart text-white bg-blue"></i> <span class="text">New Order Received</span></li>
							<li><span class="time">8 hours</span> <i class="fa fa-user text-white bg-green"></i> <span class="text">New
									User Registered</span></li>
							<li><span class="time">22 hours</span> <i class="fa fa-shopping-cart text-white bg-blue"></i> <span class="text">New Order Received</span></li> -->
						</ul>
					</div>
				</div>
			</div>

			<div class="col-xl-6 col-md-6">
				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">Support Tickets</h3>


					</div>

					<div class="comments-panel">
						<ul v-if="splashSupport.length">
							<li v-for="support in splashSupport">
								<div class="img">
									<img src="assets/img/avatars/04_40x40.png" alt="" class="rounded-circle">
								</div>

								<div class="info">
									<h3 class="h6">{{support.user.fullName}}</h3>

									<p>{{support.topic}}</p>

									<div class="action">
										<span class="status text-orange">{{support.supportStatus.status}}</span>
										<a href="/" class="btn btn-sm btn-info">Delete</a>
									</div>
								</div>
							</li>


						</ul>

						<div class="nav">
							<a href="<?php echo $this->url("admin/default", array("controller" => "admin", "action" => "support")) ?>" class="next btn-link">Older Comments <i class="fa fa-angle-double-right"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>
<script>
	let dashboard = new Vue({
		el: "#board",
		mounted() {
			this.getCustomerCount();
			this.getIntiTedBookingCount();
			this.getActiveTripCount();
			this.getSplashInitiatedBooking();
			this.getSplashCancledBooking();
			this.getSplashInTransitBooking();
			this.getSplashCompletedTrips();

			// Support
			this.getSplashSupport();

		},
		data() {
			return {
				customers: 0,
				initiatedBooking: 0,
				activeTrip: 0,

				splashInitiatedBooking: [],
				splashCanceledBooking: [],
				splashInTransitBooking: [],
				splashCompletedTrip: [],

				// Support
				splashSupport: [],

				isNotifyingCustomer: false,
			}
		},
		methods: {
			formatPHPDate(date) {
				// myDate = date.replace(/-/g, "/");
				return new Date(date);
			},
			formatPrice(value) {
				let val = (value / 1).toFixed(2).replace(',', '.')
				return val.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")
			},

			notifyCustomer(id) {
				this.isNotifyingCustomer = true;
				let formData = new FormData();
				formData.append("id", id);
				axios.post("/controller/booking/sendbookingprice", formData).then(res => {
					if (res.status = 204) {
						window.location.reload();
					}
				}).catch()
			},

			initiateBookingListLink(uid) {
				return "/controller/booking/view/" + uid
			},

			getCustomerCount() {
				axios.get('/controller/customer/allcustomercount').then(res => {
					if (res.status == 200) {
						this.customers = res.data.count;
					}
				}).catch();
			},

			getIntiTedBookingCount() {
				axios.get("/controller/booking/initiatedbookingcount").then(res => {
					if (res.status == 200) {
						this.initiatedBooking = res.data.count;
					}
				}).catch();
			},

			getActiveTripCount() {

				axios.get("/controller/booking/intransitcount").then(res => {
					if (res.status == 200) {
						this.activeTrip = res.data.data;
					}
				}).catch();
			},

			// Splassh Data
			getSplashInitiatedBooking() {
				axios.get("/controller/booking/splashinitiatedbooking").then(res => {
					if (res.status == 200) {
						this.splashInitiatedBooking = res.data.data;
					}
				}).catch();
			},

			getSplashCancledBooking() {
				axios.get("/controller/booking/splashcanceledbooking").then(res => {
					if (res.status == 200) {
						this.splashCanceledBooking = res.data.data;

					}

				}).catch();
			},

			getSplashCompletedTrips() {
				axios.get("/controller/booking/splashcompletedtrip").then(res => {
					if (res.status == 200) {
						this.splashCompletedTrip = res.data.data;
					}
				});
			},

			getSplashInTransitBooking() {
				axios.get("/controller/booking/splashtransitbooking").then(res => {
					if (res.status == 200) {
						this.splashInTransitBooking = res.data.data;
					}

				}).catch();
			},

			getSplashSupport() {
				axios.get("/controller/admin/getSplashSupport").then(res => {
					if (res.status == 200) {
						this.splashSupport = res.data.data;
					}
				}).catch();
			}
		},
	});
</script>