<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle('BAU CARS '. $this->translate('Welcome Aboard'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

        <!-- Le styles -->
<script
	src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js"></script>
<script>
          WebFont.load({
            google: {"families":["Montserrat:400,500,600,700","Noto+Sans:400,700"]},
            active: function() {
                sessionStorage.fonts = true;
            }
          });
        </script>
<!-- Favicon -->
<link rel="apple-touch-icon" sizes="180x180"
	href="assets/img/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32"
	href="assets/img/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16"
	href="assets/img/favicon-16x16.png">
        <?php
        
        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ))
            ->prependStylesheet("https://cdn.jsdelivr.net/npm/vue-toast-notification/dist/theme-default.css")
            ->prependStylesheet($this->basePath('control/assets/css/style.css'))
            ->prependStylesheet($this->basePath('control/assets/css/datatables.min.css'))
            ->prependStylesheet($this->basePath('control/assets/css/ion.rangeSlider.min.css'))
            ->prependStylesheet($this->basePath('control/assets/css/dropzone.min.css'))
            ->prependStylesheet($this->basePath('control/assets/css/weather-icons.min.css'))
            ->prependStylesheet($this->basePath('control/assets/css/horizontal-timeline.min.css'))
            ->prependStylesheet($this->basePath('control/assets/css/jquery-jvectormap.min.css'))
            ->prependStylesheet($this->basePath('control/assets/css/select2.min.css'))
            ->prependStylesheet($this->basePath('/control/assets/css/morris.min.css'))
            ->prependStylesheet($this->basePath('control/assets/css/perfect-scrollbar.min.css'))
            ->prependStylesheet($this->basePath('control/assets/css/jquery-ui.min.css'))
            ->prependStylesheet($this->basePath('control/assets/css/fontawesome-all.min.css'))
            ->prependStylesheet($this->basePath('control/assets/css/bootstrap.min.css'))?>
                      

        <!-- Scripts -->
        <?php
        
        echo $this->headScript()
            ->prependFile("https://unpkg.com/sweetalert/dist/sweetalert.min.js")
            ->prependFile("https://cdn.jsdelivr.net/npm/vue-toast-notification@0.6.2/dist/index.min.js")
            ->prependFile($this->basePath('js/axios.min.js'))
            ->prependFile($this->basePath('js/vue.js'))
            ->prependFile($this->basePath('admin/assets/vendors/js/base/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ))
            ->prependFile($this->basePath('js/html5shiv.js'), 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ));
        ?>

    </head>
	<style>
		[v-cloak]{
			display: none;
		}
	</style>
<body>

	<!-- Wrapper Start -->
	<div class="wrapper">
		<!-- Navbar Start -->
		<header class="navbar navbar-fixed">
			<!-- Navbar Header Start -->
			<div class="navbar--header">
				<!-- Logo Start -->
				<a href="index.html" class="logo"> <img src="assets/img/logo.png"
					alt="">
				</a>
				<!-- Logo End -->

				<!-- Sidebar Toggle Button Start -->
				<a href="#" class="navbar--btn" data-toggle="sidebar"
					title="Toggle Sidebar"> <i class="fa fa-bars"></i>
				</a>
				<!-- Sidebar Toggle Button End -->
			</div>
			<!-- Navbar Header End -->

			<!-- Sidebar Toggle Button Start -->
			<a href="#" class="navbar--btn" data-toggle="sidebar"
				title="Toggle Sidebar"> <i class="fa fa-bars"></i>
			</a>
			<!-- Sidebar Toggle Button End -->

			<!-- Navbar Search Start -->
			<div class="navbar--search">
				<!-- 				<form action="search-results.html"> -->
				<!-- 					<input type="search" name="search" class="form-control" -->
				<!-- 						placeholder="Search Something..." required> -->
				<!-- 					<button class="btn-link"> -->
				<!-- 						<i class="fa fa-search"></i> -->
				<!-- 					</button> -->
				<!-- 				</form> -->
			</div>
			<!-- Navbar Search End -->

			<div class="navbar--nav ml-auto">
				<ul class="nav">
					<!-- 					<li class="nav-item"><a href="#" class="nav-link"> <i -->
					<!-- 							class="fa fa-bell"></i> <span class="badge text-white bg-blue">7</span> -->
					<!-- 					</a></li> -->

					<!-- 					<li class="nav-item"><a href="mailbox_inbox.html" class="nav-link"> -->
					<!-- 							<i class="fa fa-envelope"></i> <span -->
					<!-- 							class="badge text-white bg-blue">4</span> -->
					<!-- 					</a></li> -->

					<!-- Nav Language Start -->
					<!-- 					<li class="nav-item dropdown nav-language"><a href="#" -->
					<!-- 						class="nav-link" data-toggle="dropdown"> <img -->
					<!-- 							src="assets/img/flags/us.png" alt=""> <span>English</span> <i -->
					<!-- 							class="fa fa-angle-down"></i> -->
					<!-- 					</a> -->

					<!-- 						<ul class="dropdown-menu"> -->
					<!-- 							<li><a href=""> <img src="assets/img/flags/de.png" alt=""> <span>German</span> -->
					<!-- 							</a></li> -->
					<!-- 							<li><a href=""> <img src="assets/img/flags/fr.png" alt=""> <span>French</span> -->
					<!-- 							</a></li> -->
					<!-- 							<li><a href=""> <img src="assets/img/flags/us.png" alt=""> <span>English</span> -->
					<!-- 							</a></li> -->
					<!-- 						</ul></li> -->
					<!-- Nav Language End -->

					<!-- Nav User Start -->
					<li class="nav-item dropdown nav--user online"><a href="#"
						class="nav-link" data-toggle="dropdown"> <img
							src="assets/img/avatars/01_80x80.png" alt=""
							class="rounded-circle"> <span>Admin</span> <i
							class="fa fa-angle-down"></i>
					</a>

						<ul class="dropdown-menu">
							<!-- 							<li><a href="profile.html"><i class="far fa-user"></i>Profile</a></li> -->
							<!-- 							<li><a href="mailbox_inbox.html"><i class="far fa-envelope"></i>Inbox</a></li> -->
							<!-- 							<li><a href="#"><i class="fa fa-cog"></i>Settings</a></li> -->
							<!-- 							<li class="dropdown-divider"></li> -->
							<!-- 							<li><a href="lock-screen.html"><i class="fa fa-lock"></i>Lock -->
							<!-- 									Screen</a></li> -->
							<li><a href="<?php  echo $this->url("logout")?>"><i
									class="fa fa-power-off"></i>Logout</a></li>
						</ul></li>
					<!-- Nav User End -->
				</ul>
			</div>
		</header>
		<!-- Navbar End -->

		<!-- Sidebar Start -->
		<aside class="sidebar" data-trigger="scrollbar">
			<!-- Sidebar Profile Start -->
			<div class="sidebar--profile">
				<div class="profile--img">
					<a href="profile.html"> <img src="assets/img/avatars/01_80x80.png"
						alt="" class="rounded-circle">
					</a>
				</div>

				<div class="profile--name">
					<a href="profile.html" class="btn-link"><?php
    echo ($this->identity() != null ? $this->identity()->getFullName() : "")?></a>
				</div>

				<div class="profile--nav">
					<ul class="nav">
						<!-- 						<li class="nav-item"><a href="profile.html" class="nav-link" -->
						<!-- 							title="User Profile"> <i class="fa fa-user"></i> -->
						<!-- 						</a></li> -->
						<!-- 						<li class="nav-item"><a href="lock-screen.html" class="nav-link" -->
						<!-- 							title="Lock Screen"> <i class="fa fa-lock"></i> -->
						<!-- 						</a></li> -->
						<!-- 						<li class="nav-item"><a href="mailbox_inbox.html" class="nav-link" -->
						<!-- 							title="Messages"> <i class="fa fa-envelope"></i> -->
						<!-- 						</a></li> -->
						<li class="nav-item"><a href="<?php  echo $this->url("logout")?>"
							class="nav-link" title="Logout"> <i class="fa fa-sign-out-alt"></i>
						</a></li>
					</ul>
				</div>
			</div>
			<!-- Sidebar Profile End -->

			<!-- Sidebar Navigation Start -->
			<div class="sidebar--nav">
				<ul>
					<li>
						<ul>
							<li class="active"><a
								href="<?php echo $this->url("admin/default", ["controller"=>"admin"])?>">
									<i class="fa fa-home"></i> <span>Dashboard</span>
							</a></li>
							<li class="active"><a
								href="<?php echo $this->url("admin/default", ["controller"=>"booking", "action"=>"board"]) ?>">
									<i class="fa fa-road"></i> <span>Bookings</span>
							</a></li>
							<li class="active"><a
								href="<?php echo $this->url("admin/default", ["controller"=>"logistics", "action"=>"index"]) ?>">
									<i class="fa fa-road"></i> <span>Logistics</span>
							</a></li>
							
							<li class="active"><a
								href="<?php echo $this->url("admin/default", ["controller"=>"customer", "action"=>"board"])?>">
									<i class="fa fa-user"></i> <span>Customers</span>
							</a></li>
							<li class="active"><a
								href="<?php  echo $this->url("admin/default", ["controller"=>"driver", "action"=>"drivers"])?>">
									<i class="fa fa-spinner"></i> <span>Driver</span>
							</a></li>

							<li class="active"><a
								href="<?php  echo $this->url("admin/default", ["controller"=>"riders", "action"=>"riders"])?>">
									<i class="fa fa-spinner"></i> <span>Riders</span>
							</a></li>
							<li class="active"><a
								href="<?php  echo $this->url("admin/default", ["controller"=>"car", "action"=>"index"]) ?>">
									<i class="fa fa-car"></i> <span>Cars</span>
							</a></li>
							<li class="active"><a
								href="<?php echo $this->url("admin/default", ["controller"=>"settings", "action"=>"config"])?>">
									<i class="fa fa-wrench"></i> <span>Settings</span>
							</a></li>


						</ul>
					</li>








				</ul>
			</div>
			<!-- Sidebar Navigation End -->

			<!-- Sidebar Widgets Start -->
			<div id="statistics" class="sidebar--widgets">
				<div class="widget">
					<h3 class="h6 widget--title">Information Summary</h3>

					<!-- Summary Widget Start -->
					<div class="summary--widget">
						<div class="summary--item">
							<p class="summary--chart" data-trigger="sparkline"
								data-type="bar" data-width="5" data-height="38"
								data-color="#2bb3c0">5,6,7,9,15,5,6,7,9,11,7,9,11,7,9,9,3,2</p>

							<p class="summary--title">Daily Traffic</p>
							<p class="summary--stats">307.512</p>
						</div>

						<div class="summary--item">
							<p class="summary--chart" data-trigger="sparkline"
								data-type="bar" data-width="5" data-height="38"
								data-color="#e16123">2,3,7,7,9,11,9,7,9,11,9,7,5,4,9,7,5,4</p>

							<p class="summary--title">Average Usage</p>
							<p class="summary--stats">2,371,527</p>
						</div>

						<div class="summary--item">
							<p class="summary--chart" data-trigger="sparkline"
								data-type="bar" data-width="5" data-height="38"
								data-color="#cccccc">5,6,7,9,15,5,6,7,9,11,7,9,11,7,9,9,3,2</p>

							<p class="summary--title">Disk Usage</p>
							<p class="summary--stats">37.5%</p>
						</div>

						<div class="summary--item">
							<p class="summary--chart" data-trigger="sparkline"
								data-type="bar" data-width="5" data-height="38"
								data-color="#009378">2,3,7,7,9,11,9,7,9,11,9,7,5,4,9,7,5,4</p>

							<p class="summary--title">CPU Usage</p>
							<p class="summary--stats">37.05-32</p>
						</div>

						<div class="summary--item">
							<p class="summary--chart" data-trigger="sparkline"
								data-type="bar" data-width="5" data-height="38"
								data-color="#ff4040">5,6,7,9,15,5,6,7,9,11,7,9,11,7,9,9,3,2</p>

							<p class="summary--title">Memory Usage</p>
							<p class="summary--stats">37.05%</p>
						</div>
					</div>
					<!-- Summary Widget End -->
				</div>
			</div>
			<script>

			</script>
			<!-- Sidebar Widgets End -->
		</aside>
		<!-- Sidebar End -->

		<!-- Main Container Start -->
		<main class="main--container"> <!-- Page Header Start --> <!-- Page Header End -->
		<!-- Main Content Start -->
		
		<?php  echo $this->content?>
		
		<!-- Main Content End --> <!-- Main Footer Start --> <footer
			class="main--footer main--footer-light">
			<p>
				Copyright &copy; <a href="#">Bau Cars Limited </a>. All Rights
				Reserved.
			</p>
		</footer> <!-- Main Footer End --> </main>
		<!-- Main Container End -->
	</div>
	<!-- Wrapper End -->

	<!-- Scripts -->
	<script src="/control/assets/js/jquery.min.js"></script>
	<script src="/control/assets/js/jquery-ui.min.js"></script>
	<script src="/control/assets/js/bootstrap.bundle.min.js"></script>
	<script src="/control/assets/js/perfect-scrollbar.min.js"></script>
	<script src="/control/assets/js/jquery.sparkline.min.js"></script>
	<script src="/control/assets/js/raphael.min.js"></script>
	<script src="/control/assets/js/morris.min.js"></script>
	<script src="/control/assets/js/select2.min.js"></script>
	<script src="/control/assets/js/jquery-jvectormap.min.js"></script>
	<script src="/control/assets/js/jquery-jvectormap-world-mill.min.js"></script>
	<script src="/control/assets/js/horizontal-timeline.min.js"></script>
	<script src="/control/assets/js/jquery.validate.min.js"></script>
	<script src="/control/assets/js/jquery.steps.min.js"></script>
	<script src="/control/assets/js/dropzone.min.js"></script>
	<script src="/control/assets/js/ion.rangeSlider.min.js"></script>
	<script src="/control/assets/js/datatables.min.js"></script>
	<script src="/control/assets/js/main.js"></script>

	<!-- Page Level Scripts -->

</body>
</html>
