<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle('BAU CARS '. $this->translate('Welcome Aboard'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

        <!-- Le styles -->
<link rel="stylesheet"
	href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
	integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
	crossorigin="anonymous">
        <?php
        
        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ))
            ->
        // ->prependStylesheet($this->basePath('assets/css/responsive.css'))
        // ->prependStylesheet($this->basePath('assets/style.css'))
        // ->prependStylesheet($this->basePath('assets/css/reset.css'))
        // ->prependStylesheet($this->basePath('assets/css/font-awesome.css'))
        // ->prependStylesheet($this->basePath('assets/css/plugins/gijgo.css'))
        
        prependStylesheet($this->basePath('blue/assets/css/templatemo-chain-app-dev.css'))
            ->prependStylesheet($this->basePath('blue/assets/css/animated.css'))
            ->prependStylesheet($this->basePath('blue/assets/css/templatemo-chain-app-dev.css'))
            ->prependStylesheet($this->basePath('blue/vendor/bootstrap/css/bootstrap.min.css'))?>
                      

        <!-- Scripts -->
        <?php
        
        // echo $this->headScript()
        // ->prependFile("https://unpkg.com/sweetalert/dist/sweetalert.min.js")
        // ->prependFile("https://cdn.jsdelivr.net/npm/vue-toast-notification@0.6.2/dist/index.min.js")
        // ->prependFile($this->basePath('js/axios.min.js'))
        // ->prependFile($this->basePath('js/vue.js'))
        // ->prependFile($this->basePath('js/bootstrap.min.js'))
        // ->prependFile($this->basePath('js/jquery.min.js'))
        // ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array(
        // 'conditional' => 'lt IE 9'
        // ))
        // ->prependFile($this->basePath('js/html5shiv.js'), 'text/javascript', array(
        // 'conditional' => 'lt IE 9'
        // ));
        ?>

    </head>
<body>
	<!-- ***** Preloader Start ***** -->
	<div id="js-preloader" class="js-preloader">
		<div class="preloader-inner">
			<span class="dot"></span>
			<div class="dots">
				<span></span> <span></span> <span></span>
			</div>
		</div>
	</div>

	<!-- ***** Header Area Start ***** -->
	<header class="header-area header-sticky wow slideInDown"
		data-wow-duration="0.75s" data-wow-delay="0s">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<nav class="main-nav">
						<!-- ***** Logo Start ***** -->
						<a href="<?php echo $this->url("application") ?>" class="logo"> <img
							src="/assets/img/logo-black.png" alt="Bau Cars">
						</a>
						<!-- ***** Logo End ***** -->
						<!-- ***** Menu Start ***** -->
						<ul class="nav">
							<li class="scroll-to-section"><a href="#top" class="active">Home</a></li>
							<li class="scroll-to-section"><a href="#services">Services</a></li>
							<li class="scroll-to-section"><a href="#about">About</a></li>
<!-- 							<li class="scroll-to-section"><a href="#pricing">Pricing</a></li> -->
							<li class="scroll-to-section"><a href="#newsletter">Newsletter</a></li>
							<li><div class="gradient-button">
									<a  href="<?php echo $this->url("login") ?>"><i
										class="fa fa-sign-in-alt"></i> Sign In Now</a>
								</div></li>
						</ul>
						<a class='menu-trigger'> <span>Menu</span>
						</a>
						<!-- ***** Menu End ***** -->
					</nav>
				</div>
			</div>
		</div>
	</header>
	<!-- ***** Header Area End ***** -->


	<div id="modal" class="popupContainer" style="display: none;">
		<div class="popupHeader">
			<span class="header_title">Login</span> <span class="modal_close"><i
				class="fa fa-times"></i></span>
		</div>

		<section class="popupBody">
			<!-- Social Login -->
			<div class="social_login">
				<div class="">
					<a href="#" class="social_box fb"> <span class="icon"><i
							class="fab fa-facebook"></i></span> <span class="icon_title">Connect
							with Facebook</span>

					</a> <a href="#" class="social_box google"> <span class="icon"><i
							class="fab fa-google-plus"></i></span> <span class="icon_title">Connect
							with Google</span>
					</a>
				</div>

				<div class="centeredText">
					<span>Or use your Email address</span>
				</div>

				<div class="action_btns">
					<div class="one_half">
						<a href="#" id="login_form" class="btn">Login</a>
					</div>
					<div class="one_half last">
						<a href="#" id="register_form" class="btn">Sign up</a>
					</div>
				</div>
			</div>

			<!-- Username & Password Login form -->
			<div class="user_login">
				<form>
					<label>Email / Username</label> <input type="text" /> <br /> <label>Password</label>
					<input type="password" /> <br />

					<div class="checkbox">
						<input id="remember" type="checkbox" /> <label for="remember">Remember
							me on this computer</label>
					</div>

					<div class="action_btns">
						<div class="one_half">
							<a href="#" class="btn back_btn"><i
								class="fa fa-angle-double-left"></i> Back</a>
						</div>
						<div class="one_half last">
							<a href="#" class="btn btn_red">Login</a>
						</div>
					</div>
				</form>

				<a href="#" class="forgot_password">Forgot password?</a>
			</div>

			<!-- Register Form -->
			<div class="user_register">
				<form>
					<label>Full Name</label> <input type="text" /> <br /> <label>Email
						Address</label> <input type="email" /> <br /> <label>Password</label>
					<input type="password" /> <br />

					<div class="checkbox">
						<input id="send_updates" type="checkbox" /> <label
							for="send_updates">Send me occasional email updates</label>
					</div>

					<div class="action_btns">
						<div class="one_half">
							<a href="#" class="btn back_btn"><i
								class="fa fa-angle-double-left"></i> Back</a>
						</div>
						<div class="one_half last">
							<a href="#" class="btn btn_red">Register</a>
						</div>
					</div>
				</form>
			</div>
		</section>
	</div>

	<?php  echo $this->content ?>

	
	<footer id="newsletter">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2">
					<div class="section-heading">
						<h4>Join our mailing list to receive the news &amp; latest trends</h4>
					</div>
				</div>
				<div class="col-lg-6 offset-lg-3">
					<form id="search" action="#" method="GET">
						<div class="row">
							<div class="col-lg-6 col-sm-6">
								<fieldset>
									<input type="address" name="address" class="email"
										placeholder="Email Address..." autocomplete="on" required>
								</fieldset>
							</div>
							<div class="col-lg-6 col-sm-6">
								<fieldset>
									<button type="submit" class="main-button">
										Subscribe Now <i class="fa fa-angle-right"></i>
									</button>
								</fieldset>
							</div>
						</div>
					</form>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-3">
					<div class="footer-widget">
						<h4>Contact Us</h4>
						<p>Odua Office Complex, Blk 16 Suite 7&8, New Garage Ojota <br> Lago, Nigeria</p>
						<p>
							<a href="#">+234 (0)8052536443 <br> (0)8052536544</a>
						</p>
						<p>
							<a href="#">support@baucars.com</a>
						</p>
					</div>
				</div>
				<div class="col-lg-3">
					<div class="footer-widget">
						<h4>About Us</h4>
<!-- 						<ul> -->
<!-- 							<li><a href="#">Home</a></li> -->
<!-- 							<li><a href="#">Services</a></li> -->
<!-- 							<li><a href="#">About</a></li> -->
<!-- 							<li><a href="#">Testimonials</a></li> -->
<!-- 							<li><a href="#">Pricing</a></li> -->
<!-- 						</ul> -->
						<ul>
<!-- 							<li><a href="#">About</a></li> -->
<!-- 							<li><a href="#">Testimonials</a></li> -->
<!-- 							<li><a href="#">Pricing</a></li> -->
						</ul>
					</div>
				</div>
				<div class="col-lg-3">
					<div class="footer-widget">
						<h4>Useful Links</h4>
						<ul>
<!-- 							<li><a href="#">Free Apps</a></li> -->
<!-- 							<li><a href="#">App Engine</a></li> -->
<!-- 							<li><a href="#">Programming</a></li> -->
<!-- 							<li><a href="#">Development</a></li> -->
<!-- 							<li><a href="#">App News</a></li> -->
						</ul>
						<ul>
<!-- 							<li><a href="#">App Dev Team</a></li> -->
<!-- 							<li><a href="#">Digital Web</a></li> -->
<!-- 							<li><a href="#">Normal Apps</a></li> -->
						</ul>
					</div>
				</div>
				<div class="col-lg-3">
					<div class="footer-widget">
						<h4>About Our Company</h4>
						<div class="logo">
							<img src="/assets/img/logo.png" alt="">
						</div>
						<p>Odua Office Complex, Blk 16 Suite 7&8, New Garage Ojota <br> Lago, Nigeria</p>
					</div>
				</div>
				<div class="col-lg-12">
					<div class="copyright-text">
						<p>
							Copyright © 2022 Baucars Limited. All Rights Reserved. <br>Design:
							<a href="https://baucars.com/" target="_blank"
								title="css templates">Bau Cars Limited</a>
						</p>
					</div>
				</div>
			</div>
		</div>
	</footer>



	<!--=======================Javascript============================-->
	<script src="/blue/vendor/jquery/jquery.min.js"></script>
	<script src="/blue/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
	<script src="/blue/assets/js/owl-carousel.js"></script>
	<script src="/blue/assets/js/animation.js"></script>
	<script src="/blue/assets/js/imagesloaded.js"></script>
	<script src="/blue/assets/js/popup.js"></script>
	<script src="/blue/assets/js/custom.js"></script>
	
	
	
        <?php echo $this->inlineScript() ?>
    </body>
</html>
