<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle('BAU CARS '. $this->translate('Welcome Aboard'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

        <!-- Le styles -->
<script
	src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js"></script>
<script>
          WebFont.load({
            google: {"families":["Montserrat:400,500,600,700","Noto+Sans:400,700"]},
            active: function() {
                sessionStorage.fonts = true;
            }
          });
        </script>
<!-- Favicon -->
<link rel="apple-touch-icon" sizes="180x180"
	href="assets/img/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32"
	href="assets/img/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16"
	href="assets/img/favicon-16x16.png">
        <?php
        
        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ))
           
            
            ->prependStylesheet($this->basePath('soon/css/main.css'))
            ->prependStylesheet($this->basePath('soon/css/util.css'))
            ->prependStylesheet($this->basePath('soon/vendor/select2/select2.min.css'))
            ->prependStylesheet($this->basePath('soon/vendor/animate/animate.css'))
            ->prependStylesheet($this->basePath('soon/fonts/font-awesome-4.7.0/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('soon/vendor/bootstrap/css/bootstrap.min.css'))?>
                      

     

    </head>
<body>

	<div class="flex-w flex-str size1 overlay1">
		<div
			class="flex-w flex-col-sb wsize1 bg0 p-l-65 p-t-37 p-b-50 p-r-80 respon1">
			<div class="wrappic1">
				<a href="<?php echo $this->url("application")?>"> <img src="/assets/img/logo-black.png" alt="Baucars Logo">
				</a>
			</div>

			<div class="w-full flex-c-m p-t-80 p-b-90">
				<div class="wsize2">
					<h3 class="l1-txt1 p-b-34 respon3">Making It Better</h3>

					<p class="m2-txt1 p-b-46"><a href="<?php echo $this->url("application")?>"> Go Back Home</a></p>

					
				</div>
			</div>

			<div class="flex-w">
				<a href="#" class="size3 flex-c-m how-social trans-04 m-r-15 m-b-10">
					<i class="fa fa-facebook"></i>
				</a> <a href="#"
					class="size3 flex-c-m how-social trans-04 m-r-15 m-b-10"> <i
					class="fa fa-twitter"></i>
				</a> <a href="#"
					class="size3 flex-c-m how-social trans-04 m-r-15 m-b-10"> <i
					class="fa fa-youtube-play"></i>
				</a>
			</div>
		</div>


		<div class="wsize1 simpleslide100-parent respon2">
			<!--  -->
			<div class="simpleslide100">
				<div class="simpleslide100-item bg-img1"
					style="background-image: url('/soon/images/bg01.jpg');"></div>
				<div class="simpleslide100-item bg-img1"
					style="background-image: url('/soon/images/bg02.jpg');"></div>
				<div class="simpleslide100-item bg-img1"
					style="background-image: url('/soon/images/bg03.jpg');"></div>
			</div>
		</div>
	</div>





	<!--===============================================================================================-->
	<script src="/soon/vendor/jquery/jquery-3.2.1.min.js"></script>
	<!--===============================================================================================-->
	<script src="/soon/vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
	<!--===============================================================================================-->
	<script src="/soon/vendor/select2/select2.min.js"></script>
	<!--===============================================================================================-->
	<script src="/soon/vendor/tilt/tilt.jquery.min.js"></script>
	<!--===============================================================================================-->
	<script src="/soon/js/main.js"></script>

</body>
</html>
