<?php
?>

<section id="footer-area">
	<!-- Footer Widget Start -->
	<div class="footer-widget-area">
		<div class="container">
			<div class="row">
				<!-- Single Footer Widget Start -->
				<div class="col-lg-4 col-md-6">
					<div class="single-footer-widget">
						<h2>About Us</h2>
						<div class="widget-body">
							<img src="assets/img/logo.png" alt="JSOFT">
							<p>Bau Cars top priority and Values centers on who we are and
								what we do. We make sure everything about car/minicab hire is as
								simple and transparent as possible; while also providing
								excellent service and great value for money.
							
							
							<div class="newsletter-area">
								<form action="index.html">
									<input type="email" placeholder="Subscribe Our Newsletter">
									<button type="submit" class="newsletter-btn">
										<i class="fa fa-send"></i>
									</button>
								</form>
							</div>

						</div>
					</div>
				</div>
				<!-- Single Footer Widget End -->

				<!-- Single Footer Widget Start -->
				<div class="col-lg-4 col-md-6">
					<div class="single-footer-widget">
						<h2></h2>
						<!-- <div class="widget-body">
							<ul class="recent-post">
								<li><a href="#"> Hello Bangladesh! <i class="fa fa-long-arrow-right"></i>
									</a></li>
								<li><a href="#"> Lorem ipsum dolor sit amet <i class="fa fa-long-arrow-right"></i>
									</a></li>
								<li><a href="#"> Hello Bangladesh! <i class="fa fa-long-arrow-right"></i>
									</a></li>
								<li><a href="#"> consectetur adipisicing elit? <i class="fa fa-long-arrow-right"></i>
									</a></li>
							</ul>
						</div> -->
					</div>
				</div>
				<!-- Single Footer Widget End -->

				<!-- Single Footer Widget Start -->
				<div class="col-lg-4 col-md-6">
					<div class="single-footer-widget">
						<h2>get touch</h2>
						<div class="widget-body">
							<p></p>

							<ul class="get-touch">
								<li><i class="fa fa-map-marker"></i> Odua Office Complex, Blk
									16, suite 7&8, New garage, ojota</li>
								<li><i class="fa fa-mobile"></i> +234 (0)8052536443</li>
								<li><i class="fa fa-envelope"></i> support@baucars.com</li>
							</ul>
							<!-- 								<a href="https://goo.gl/maps/b5mt45MCaPB2" class="map-show" -->
							<!-- 									target="_blank">Show Location</a> -->
						</div>
					</div>
				</div>
				<!-- Single Footer Widget End -->
			</div>
		</div>
	</div>
	<!-- Footer Widget End -->

	<!-- Footer Bottom Start -->
	<div class="footer-bottom-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 text-center">
					<p>
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						Copyright &copy;
						<script>
							document.write(new Date().getFullYear());
						</script>
						All rights reserved <a href="" target="_blank">BAU CARS</a>
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					</p>
				</div>
			</div>
		</div>
	</div>
	<!-- Footer Bottom End -->
</section>