<?php
?>

<header id="header-area" class="fixed-top">
	<!--== Header Top Start ==-->
	<div id="header-top" class="d-none d-xl-block">
		<div class="container">
			<div class="row">
				<!--== Single HeaderTop Start ==-->
				<div class="col-lg-3 text-left">
					<i class="fa fa-map-marker"></i> Odua Office Complex, Blk 16 Suite 7&8, New Garage Ojota <br> Lago, Nigeria
				</div>
				<!--== Single HeaderTop End ==-->

				<!--== Single HeaderTop Start ==-->
				<div class="col-lg-3 text-center">
					<i class="fa fa-mobile"></i> +234 (0)8052536443 <br> (0)8052536544
				</div>
				<!--== Single HeaderTop End ==-->

				<!--== Single HeaderTop Start ==-->
				<div class="col-lg-3 text-center">
					<i class="fa fa-clock-o"></i> 24Hrs Service
				</div>
				<!--== Single HeaderTop End ==-->

				<!--== Social Icons Start ==-->
				<div class="col-lg-3 text-right">
					<div class="header-social-icons">
						<a href="https://web.facebook.com/baucarsltd"><i class="fa fa-facebook"></i></a> <a href="#"><i class="fa fa-linkedin"></i></a>
					</div>
				</div>
				<!--== Social Icons End ==-->
			</div>
		</div>
	</div>
	<!--== Header Top End ==-->

	<!--== Header Bottom Start ==-->
	<div id="header-bottom">
		<div class="container">
			<div class="row">
				<!--== Logo Start ==-->
				<div class="col-lg-4">
					<a href="<?php echo $this->url("application") ?>" class="logo"> <img src="/assets/img/logo.png" alt="JSOFT">
					</a>
				</div>
				<!--== Logo End ==-->

				<!--== Main Menu Start ==-->
				<div class="col-lg-8 d-none d-xl-block">
					<nav class="mainmenu alignright">
						<ul>
							<li><a href="<?php echo $this->url("application") ?>">Home</a> <!-- 									<ul> -->
								<!-- 										<li><a href="index.html">Home 1</a></li> -->
								<!-- 										<li><a href="index2.html">Home 2</a></li> -->
								<!-- 										<li><a href="index3.html">Home 3</a></li> -->
								<!-- 									</ul> -->
								<!-- 									</li> -->

							<li><a href="<?php echo $this->url("application/default", array("action" => "about")) ?>">About</a></li>
							<li><a href="<?php echo $this->url("application/default", ["action" => "services"]) ?>">Services</a></li>
							<li><a href="<?php echo $this->url("application/default", ["action" => "package"]) ?>">Logistics</a></li>
							
								<!-- 									<ul> -->
								<!-- 										<li><a href="car-left-sidebar.html">Car Left Sidebar</a></li> -->
								<!-- 										<li><a href="car-right-sidebar.html">Car Right Sidebar</a></li> -->
								<!-- 										<li><a href="car-without-sidebar.html">Car Without Sidebar</a></li> -->
								<!-- 										<li><a href="car-details.html">Car Details</a></li> -->
								<!-- 									</ul> -->
								<!-- 									</li> -->

							<li><a href="<?php echo $this->url("application/default", ["action" => "contact"]) ?>">Contact</a></li>
							<li><a href="<?php echo $this->url("login") ?>">My Account</a></li>
							
						</ul>
					</nav>
				</div>
				<!--== Main Menu End ==-->
			</div>
		</div>
	</div>
	<!--== Header Bottom End ==-->
</header>