<?php
echo $this->headtitle("View Customer Details");
?>
<div id="viewCustomer">
	<section class="page--header">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-6">
					<!-- Page Title Start -->
					<h2 class="page--title h5">Customer Profile</h2>
					<!-- Page Title End -->

					<ul class="breadcrumb">
						<li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
						<li class="breadcrumb-item"><span>Customer</span></li>
						<li class="breadcrumb-item active"><span>Profile</span></li>
					</ul>
				</div>


			</div>
		</div>
	</section>

	<section class="main--content">
		<div class="row gutter-20">
			<div class="col-lg-8">
				<?php  echo $this->partial("admin-customer-top", ["user"=>$user])?>

				
				<!-- Panel Start -->
				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">Functionality</h3>
					</div>

					<div class="panel-content panel-activity">
						

						
					</div>
				</div>
				<!-- Panel End -->
				
				
			</div>

            
            <?php  echo $this->partial("admin-customer-sidebar"); ?>
        </div>
	</section>
</div>
