<?php
echo $this->headtitle("About Us");

?>

<section id="page-title-area" class="section-padding overlay">
	<div class="container">
		<div class="row">
			<!-- Page Title Start -->
			<div class="col-lg-12">
				<div class="section-title  text-center">
					<h2>About US</h2>
					<span class="title-line"><i class="fa fa-car"></i></span>
					<!-- 					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p> -->
				</div>
			</div>
			<!-- Page Title End -->
		</div>
	</div>
</section>


<section id="about-area" class="section-padding">
	<div class="container">
		<div class="row">
			<!-- Section Title Start -->
			<div class="col-lg-12">
				<div class="section-title  text-center">
					<h2>About us</h2>
					<span class="title-line"><i class="fa fa-car"></i></span>
					<p>Your secured and comfortable riding plug</p>
				</div>
			</div>
			<!-- Section Title End -->
		</div>

		<div class="row">
			<!-- About Content Start -->
			<div class="col-lg-6">
				<div class="display-table">
					<div class="display-table-cell">
						<div class="about-content">
							<p>Bau Cars top priority and Values centers on who we are and
								what we do. We make sure everything about car/minicab hire is as
								simple and transparent as possible; while also providing
								excellent service and great value for money.</p>
							<p>Our core philosophy centres around customers satisfaction,
								security and comfortability, thus we constantly strive to
								improve both our products and services.</p>
							<p>We also provides flexibility of having cars promptly anytime
								you are hiring anywhere in Nigeria and also when booking from
								around the world.</p>
						</div>
					</div>
				</div>
			</div>
			<!-- About Content End -->

			<!-- About Video Start -->
			<div class="col-lg-6">
				<div class="about-image">
					<img src="assets/img/home-2-about.png" alt="JSOFT">
				</div>
			</div>
			<!-- About Video End -->
		</div>

		<!-- About Fretutes Start -->
		<div class="about-feature-area">
			<div class="row">
				<!-- Single Fretutes Start -->
				<div class="col-lg-4">
					<div class="about-feature-item active">
						<i class="fa fa-car"></i>
						<h3>SECURITY</h3>
						<p>At Bau cars Limited, our prospective riders personal and
							valuables security is of paramount important to us.</p>
						<p>All our drivers are specially trained on one-to-one practical
							security driving courses such as Evasive driving techniques which
							enables them to identify potential hazards earlier and deals with
							such in a calm controlled manner.</p>
						<p>They are also effectively trained on control driving which
							teaches them on how to keep safe and be aware of any possible
							threat, anti- car jacking and simple steps on how to minimise the
							risk of personal attack.</p>
					</div>
				</div>
				<!-- Single Fretutes End -->

				<!-- Single Fretutes Start -->
				<div class="col-lg-4">
					<div class="about-feature-item">
						<i class="fa fa-car"></i>
						<h3>SAFETY</h3>
						<p>At Bau cars Limited, our drivers are equipped with good
							training on Defensive driving, which is also known as Driving
							safety which enables them in preventing accidents and not to also
							break the law while on the road.</p>
					</div>
				</div>
				<!-- Single Fretutes End -->

				<!-- Single Fretutes Start -->
				<div class="col-lg-4">
					<div class="about-feature-item">
						<i class="fa fa-car"></i>
						<h3>COMFORT</h3>
						<p>At Bau cars Limited, one of our watchword is that "A car with
							very good ride quality is also a comfortable car to ride in. As
							the comfort of any vehicle is also very important for safety.</p>

						<p>Our Driver's have absolute control of their cars at all times
							and in this way less road disturbance can impact their ability to
							control their vehicles.</p>

						<p>All our cars have good ambience which results in better
							performance by our drivers and also improving the safety of all
							our riders.</p>
					</div>
				</div>
				<!-- Single Fretutes End -->
			</div>
		</div>
		<!-- About Fretutes End -->
	</div>
</section>
<!--== About Page Content End ==-->