<?php echo $this->headtitle("Welcome to Baucars") ?>
<div class="main-banner wow fadeIn" id="top" data-wow-duration="1s" data-wow-delay="0.5s">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="row">
            <div class="col-lg-6 align-self-center">
              <div class="left-content show-up header-text wow fadeInLeft" data-wow-duration="1s" data-wow-delay="1s">
                <div class="row">
                  <div class="col-lg-12">
                    <h2>Get a Dispatch in 2min</h2>
<!--                     <p>Chain App Dev is an app landing page HTML5 template based on Bootstrap v5.1.3 CSS layout provided by TemplateMo, a great website to download free CSS templates.</p> -->
                  </div>
                  <div class="col-lg-12">
                    <div class="white-button first-button scroll-to-section">
                      <a href="<?php echo $this->url("login") ?>" class="btn btn-success">Book a Car <i class="fab fa-car"></i></a>
                    </div>
                    <div class="white-button scroll-to-section">
                      <a href="https://play.google.com/store/apps/details?id=com.bau.dispatch">Send A Parcel<i class="fab fa-google-play"></i></a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="right-image wow fadeInRight" data-wow-duration="1s" data-wow-delay="0.5s">
                <img src="/blue/assets/images/slider-dec.png" alt="">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="services" class="services section">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 offset-lg-2">
          <div class="section-heading  wow fadeInDown" data-wow-duration="1s" data-wow-delay="0.5s">
            <h4>Your secured and comfortable riding plug</h4>
            <img src="/blue/assets/images/heading-line-dec.png" alt="">
            <p>Bau Cars top priority and Values centers on who we are and
								what we do. We make sure everything about car/minicab hire is as
								simple and transparent as possible; while also providing
								excellent service and great value for money.</p>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <div class="service-item first-service">
            <div class="icon"></div>
            <h4>PACKAGE DELIVERY</h4>
            With our RAPID booking and delivery network system, your parcel delivery is safe and on the fly
            <div class="text-button">
<!--               <a href="#">Read More <i class="fa fa-arrow-right"></i></a> -->
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="service-item second-service">
            <div class="icon"></div>
            <h4>TAXI/MINI CAB</h4>
            <p>Bau Cars provides services to both individuals and corporate
							bodies, locally and internationally.</p>
						<p>We also offers an array of vehicles at very affordable rates.</p>
            <div class="text-button">
<!--               <a href="#">Read More <i class="fa fa-arrow-right"></i></a> -->
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="service-item third-service">
            <div class="icon"></div>
            <h4>LUXURY SERVICES</h4>
            <p>At Bau cars Limited, we don't do the regular car hiring. We
							provides a wide range of luxury services for your riding
							convenience</p>
            <div class="text-button">
<!--               <a href="#">Read More <i class="fa fa-arrow-right"></i></a> -->
            </div>
          </div>
        </div>
<!--         <div class="col-lg-3"> -->
<!--           <div class="service-item fourth-service"> -->
<!--             <div class="icon"></div> -->
<!--             <h4>24/7 Help &amp; Support</h4> -->
<!--             <p>Lorem ipsum dolor consectetur adipiscing elit sedder williamsburg photo booth quinoa and fashion axe.</p> -->
<!--             <div class="text-button"> -->
<!--               <a href="#">Read More <i class="fa fa-arrow-right"></i></a> -->
<!--             </div> -->
<!--           </div> -->
<!--         </div> -->
      </div>
    </div>
  </div>

  <div id="about" class="about-us section">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 align-self-center">
          <div class="section-heading">
            <h4>About <em>What We Do</em> &amp; Who We Are</h4>
            <img src="/blue/assets/images/heading-line-dec.png" alt="">
            <p>Our core philosophy centres around customers satisfaction,
								security and comfortability, thus we constantly strive to
								improve both our products and services.</p>
							<p>We also provides flexibility of having cars promptly anytime
								you are hiring anywhere in Nigeria and also when booking from
								around the world.</p>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="box-item">
                <h4><a href="#">Safety</a></h4>
                <p>At Bau cars Limited, our drivers are equipped with good
							training on Defensive driving, which is also known as Driving
							safety which enables them in preventing accidents and not to also
							break the law while on the road.</p>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="box-item">
                <h4><a href="#">24/7 Support &amp; Service</a></h4>
                <p>Our Drivers/Riders are availaible round the clock and They are also effectively trained on control driving which
							teaches them on how to keep safe and be aware of any possible
							threat, anti- car jacking and simple steps on how to minimise the
							risk of personal attackt</p>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="box-item">
                <h4><a href="#">SECURITY</a></h4>
               <p>At Bau cars Limited, our prospective riders personal and
							valuables security is of paramount important to us.</p>
						<p>All our drivers are specially trained on one-to-one practical
							security driving courses such as Evasive driving techniques which
							enables them to identify potential hazards earlier and deals with
							such in a calm controlled manner.</p>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="box-item">
                <h4><a href="#">COMFORT</a></h4>
               <p>At Bau cars Limited, one of our watchword is that "A car with
							very good ride quality is also a comfortable car to ride in. As
							the comfort of any vehicle is also very important for safety.</p>

						<p>Our Driver's have absolute control of their cars at all times
							and in this way less road disturbance can impact their ability to
							control their vehicles.</p>

						<p>All our cars have good ambience which results in better
							performance by our drivers and also improving the safety of all
							our riders.</p>
              </div>
            </div>
<!--             <div class="col-lg-12"> -->
<!--               <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eismod tempor idunte ut labore et dolore adipiscing  magna.</p> -->
<!--               <div class="gradient-button"> -->
<!--                 <a href="#">Start 14-Day Free Trial</a> -->
<!--               </div> -->
<!--               <span>*No Credit Card Required</span> -->
<!--             </div> -->
          </div>
        </div>
        <div class="col-lg-6">
          <div class="right-image">
            <img src="/blue/assets/images/about-right-dec.png" alt="">
          </div>
        </div>
      </div>
    </div>
  </div>

<!--   <div id="clients" class="the-clients"> -->
<!--     <div class="container"> -->
<!--       <div class="row"> -->
<!--         <div class="col-lg-8 offset-lg-2"> -->
<!--           <div class="section-heading"> -->
<!--             <h4>Check What <em>The Clients Say</em> About Our App Dev</h4> -->
<!--             <img src="/blue/assets/images/heading-line-dec.png" alt=""> -->
<!--             <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eismod tempor incididunt ut labore et dolore magna.</p> -->
<!--           </div> -->
<!--         </div> -->
<!--         <div class="col-lg-12"> -->
<!--           <div class="naccs"> -->
<!--             <div class="grid"> -->
<!--               <div class="row"> -->
<!--                 <div class="col-lg-7 align-self-center"> -->
<!--                   <div class="menu"> -->
<!--                     <div class="first-thumb active"> -->
<!--                       <div class="thumb"> -->
<!--                         <div class="row"> -->
<!--                           <div class="col-lg-4 col-sm-4 col-12"> -->
<!--                             <h4>David Martino Co</h4> -->
<!--                             <span class="date">30 November 2021</span> -->
<!--                           </div> -->
<!--                           <div class="col-lg-4 col-sm-4 d-none d-sm-block"> -->
<!--                             <span class="category">Financial Apps</span> -->
<!--                           </div> -->
<!--                           <div class="col-lg-4 col-sm-4 col-12"> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <span class="rating">4.8</span> -->
<!--                           </div> -->
<!--                         </div> -->
<!--                       </div> -->
<!--                     </div> -->
<!--                     <div> -->
<!--                       <div class="thumb"> -->
<!--                         <div class="row"> -->
<!--                           <div class="col-lg-4 col-sm-4 col-12"> -->
<!--                             <h4>Jake Harris Nyo</h4> -->
<!--                             <span class="date">29 November 2021</span> -->
<!--                           </div> -->
<!--                           <div class="col-lg-4 col-sm-4 d-none d-sm-block"> -->
<!--                             <span class="category">Digital Business</span> -->
<!--                           </div> -->
<!--                           <div class="col-lg-4 col-sm-4 col-12"> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <span class="rating">4.5</span> -->
<!--                           </div> -->
<!--                         </div> -->
<!--                       </div> -->
<!--                     </div> -->
<!--                     <div> -->
<!--                       <div class="thumb"> -->
<!--                         <div class="row"> -->
<!--                           <div class="col-lg-4 col-sm-4 col-12"> -->
<!--                             <h4>May Catherina</h4> -->
<!--                             <span class="date">27 November 2021</span> -->
<!--                           </div> -->
<!--                           <div class="col-lg-4 col-sm-4 d-none d-sm-block"> -->
<!--                             <span class="category">Business &amp; Economics</span> -->
<!--                           </div> -->
<!--                           <div class="col-lg-4 col-sm-4 col-12"> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <span class="rating">4.7</span> -->
<!--                           </div> -->
<!--                         </div> -->
<!--                       </div> -->
<!--                     </div> -->
<!--                     <div> -->
<!--                       <div class="thumb"> -->
<!--                         <div class="row"> -->
<!--                           <div class="col-lg-4 col-sm-4 col-12"> -->
<!--                             <h4>Random User</h4> -->
<!--                             <span class="date">24 November 2021</span> -->
<!--                           </div> -->
<!--                           <div class="col-lg-4 col-sm-4 d-none d-sm-block"> -->
<!--                             <span class="category">New App Ecosystem</span> -->
<!--                           </div> -->
<!--                           <div class="col-lg-4 col-sm-4 col-12"> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <span class="rating">3.9</span> -->
<!--                           </div> -->
<!--                         </div> -->
<!--                       </div> -->
<!--                     </div> -->
<!--                     <div class="last-thumb"> -->
<!--                       <div class="thumb"> -->
<!--                         <div class="row"> -->
<!--                           <div class="col-lg-4 col-sm-4 col-12"> -->
<!--                             <h4>Mark Amber Do</h4> -->
<!--                             <span class="date">21 November 2021</span> -->
<!--                           </div> -->
<!--                           <div class="col-lg-4 col-sm-4 d-none d-sm-block"> -->
<!--                             <span class="category">Web Development</span> -->
<!--                           </div> -->
<!--                           <div class="col-lg-4 col-sm-4 col-12"> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <i class="fa fa-star"></i> -->
<!--                               <span class="rating">4.3</span> -->
<!--                           </div> -->
<!--                         </div> -->
<!--                       </div> -->
<!--                     </div> -->
<!--                   </div> -->
<!--                 </div>  -->
<!--                 <div class="col-lg-5"> -->
<!--                   <ul class="nacc"> -->
<!--                     <li class="active"> -->
<!--                       <div> -->
<!--                         <div class="thumb"> -->
<!--                           <div class="row"> -->
<!--                             <div class="col-lg-12"> -->
<!--                               <div class="client-content"> -->
<!--                                 <img src="assets/images/quote.png" alt=""> -->
<!--                                 <p>“Lorem ipsum dolor sit amet, consectetur adpiscing elit, sed do eismod tempor idunte ut labore et dolore magna aliqua darwin kengan -->
<!--                                   lorem ipsum dolor sit amet, consectetur picing elit massive big blasta.”</p> -->
<!--                               </div> -->
<!--                               <div class="down-content"> -->
<!--                                 <img src="assets/images/client-image.jpg" alt=""> -->
<!--                                 <div class="right-content"> -->
<!--                                   <h4>David Martino</h4> -->
<!--                                   <span>CEO of David Company</span> -->
<!--                                 </div> -->
<!--                               </div> -->
<!--                             </div> -->
<!--                           </div> -->
<!--                         </div> -->
<!--                       </div> -->
<!--                     </li> -->
<!--                     <li> -->
<!--                       <div> -->
<!--                         <div class="thumb"> -->
<!--                           <div class="row"> -->
<!--                             <div class="col-lg-12"> -->
<!--                               <div class="client-content"> -->
<!--                                 <img src="assets/images/quote.png" alt=""> -->
<!--                                 <p>“CTO, Lorem ipsum dolor sit amet, consectetur adpiscing elit, sed do eismod tempor idunte ut labore et dolore magna aliqua darwin kengan -->
<!--                                   lorem ipsum dolor sit amet, consectetur picing elit massive big blasta.”</p> -->
<!--                               </div> -->
<!--                               <div class="down-content"> -->
<!--                                 <img src="assets/images/client-image.jpg" alt=""> -->
<!--                                 <div class="right-content"> -->
<!--                                   <h4>Jake H. Nyo</h4> -->
<!--                                   <span>CTO of Digital Company</span> -->
<!--                                 </div> -->
<!--                               </div> -->
<!--                             </div> -->
<!--                           </div> -->
<!--                         </div> -->
<!--                       </div> -->
<!--                     </li> -->
<!--                     <li> -->
<!--                       <div> -->
<!--                         <div class="thumb"> -->
<!--                           <div class="row"> -->
<!--                             <div class="col-lg-12"> -->
<!--                               <div class="client-content"> -->
<!--                                 <img src="assets/images/quote.png" alt=""> -->
<!--                                 <p>“May, Lorem ipsum dolor sit amet, consectetur adpiscing elit, sed do eismod tempor idunte ut labore et dolore magna aliqua darwin kengan -->
<!--                                   lorem ipsum dolor sit amet, consectetur picing elit massive big blasta.”</p> -->
<!--                               </div> -->
<!--                               <div class="down-content"> -->
<!--                                 <img src="assets/images/client-image.jpg" alt=""> -->
<!--                                 <div class="right-content"> -->
<!--                                   <h4>May C.</h4> -->
<!--                                   <span>Founder of Catherina Co.</span> -->
<!--                                 </div> -->
<!--                               </div> -->
<!--                             </div> -->
<!--                           </div> -->
<!--                         </div> -->
<!--                       </div> -->
<!--                     </li> -->
<!--                     <li> -->
<!--                       <div> -->
<!--                         <div class="thumb"> -->
<!--                           <div class="row"> -->
<!--                             <div class="col-lg-12"> -->
<!--                               <div class="client-content"> -->
<!--                                 <img src="assets/images/quote.png" alt=""> -->
<!--                                 <p>“Lorem ipsum dolor sit amet, consectetur adpiscing elit, sed do eismod tempor idunte ut labore et dolore magna aliqua darwin kengan -->
<!--                                   lorem ipsum dolor sit amet, consectetur picing elit massive big blasta.”</p> -->
<!--                               </div> -->
<!--                               <div class="down-content"> -->
<!--                                 <img src="assets/images/client-image.jpg" alt=""> -->
<!--                                 <div class="right-content"> -->
<!--                                   <h4>Random Staff</h4> -->
<!--                                   <span>Manager, Digital Company</span> -->
<!--                                 </div> -->
<!--                               </div> -->
<!--                             </div> -->
<!--                           </div> -->
<!--                         </div> -->
<!--                       </div> -->
<!--                     </li> -->
<!--                     <li> -->
<!--                       <div> -->
<!--                         <div class="thumb"> -->
<!--                           <div class="row"> -->
<!--                             <div class="col-lg-12"> -->
<!--                               <div class="client-content"> -->
<!--                                 <img src="assets/images/quote.png" alt=""> -->
<!--                                 <p>“Mark, Lorem ipsum dolor sit amet, consectetur adpiscing elit, sed do eismod tempor idunte ut labore et dolore magna aliqua darwin kengan -->
<!--                                   lorem ipsum dolor sit amet, consectetur picing elit massive big blasta.”</p> -->
<!--                               </div> -->
<!--                               <div class="down-content"> -->
<!--                                 <img src="assets/images/client-image.jpg" alt=""> -->
<!--                                 <div class="right-content"> -->
<!--                                   <h4>Mark Am</h4> -->
<!--                                   <span>CTO, Amber Do Company</span> -->
<!--                                 </div> -->
<!--                               </div> -->
<!--                             </div> -->
<!--                           </div> -->
<!--                         </div> -->
<!--                       </div> -->
<!--                     </li> -->
<!--                   </ul> -->
<!--                 </div>           -->
<!--               </div> -->
<!--             </div> -->
<!--           </div> -->
<!--         </div> -->
<!--       </div> -->
<!--     </div> -->
<!--   </div> -->

<!--   <div id="pricing" class="pricing-tables"> -->
<!--     <div class="container"> -->
<!--       <div class="row"> -->
<!--         <div class="col-lg-8 offset-lg-2"> -->
<!--           <div class="section-heading"> -->
<!--             <h4>We Have The Best Pre-Order <em>Prices</em> You Can Get</h4> -->
<!--             <img src="assets/images/heading-line-dec.png" alt=""> -->
<!--             <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eismod tempor incididunt ut labore et dolore magna.</p> -->
<!--           </div> -->
<!--         </div> -->
<!--         <div class="col-lg-4"> -->
<!--           <div class="pricing-item-regular"> -->
<!--             <span class="price">$12</span> -->
<!--             <h4>Standard Plan App</h4> -->
<!--             <div class="icon"> -->
<!--               <img src="assets/images/pricing-table-01.png" alt=""> -->
<!--             </div> -->
<!--             <ul> -->
<!--               <li>Lorem Ipsum Dolores</li> -->
<!--               <li>20 TB of Storage</li> -->
<!--               <li class="non-function">Life-time Support</li> -->
<!--               <li class="non-function">Premium Add-Ons</li> -->
<!--               <li class="non-function">Fastest Network</li> -->
<!--               <li class="non-function">More Options</li> -->
<!--             </ul> -->
<!--             <div class="border-button"> -->
<!--               <a href="#">Purchase This Plan Now</a> -->
<!--             </div> -->
<!--           </div> -->
<!--         </div> -->
<!--         <div class="col-lg-4"> -->
<!--           <div class="pricing-item-pro"> -->
<!--             <span class="price">$25</span> -->
<!--             <h4>Business Plan App</h4> -->
<!--             <div class="icon"> -->
<!--               <img src="assets/images/pricing-table-01.png" alt=""> -->
<!--             </div> -->
<!--             <ul> -->
<!--               <li>Lorem Ipsum Dolores</li> -->
<!--               <li>50 TB of Storage</li> -->
<!--               <li>Life-time Support</li> -->
<!--               <li>Premium Add-Ons</li> -->
<!--               <li class="non-function">Fastest Network</li> -->
<!--               <li class="non-function">More Options</li> -->
<!--             </ul> -->
<!--             <div class="border-button"> -->
<!--               <a href="#">Purchase This Plan Now</a> -->
<!--             </div> -->
<!--           </div> -->
<!--         </div> -->
<!--         <div class="col-lg-4"> -->
<!--           <div class="pricing-item-regular"> -->
<!--             <span class="price">$66</span> -->
<!--             <h4>Premium Plan App</h4> -->
<!--             <div class="icon"> -->
<!--               <img src="assets/images/pricing-table-01.png" alt=""> -->
<!--             </div> -->
<!--             <ul> -->
<!--               <li>Lorem Ipsum Dolores</li> -->
<!--               <li>120 TB of Storage</li> -->
<!--               <li>Life-time Support</li> -->
<!--               <li>Premium Add-Ons</li> -->
<!--               <li>Fastest Network</li> -->
<!--               <li>More Options</li> -->
<!--             </ul> -->
<!--             <div class="border-button"> -->
<!--               <a href="#">Purchase This Plan Now</a> -->
<!--             </div> -->
<!--           </div> -->
<!--         </div> -->
<!--       </div> -->
<!--     </div> -->
<!--   </div>  -->