<?php
echo $this->headtitle("Our Cars");
?>


<!--== Page Title Area Start ==-->
<section id="page-title-area" class="section-padding overlay">
	<div class="container">
		<div class="row">
			<!-- Page Title Start -->
			<div class="col-lg-12">
				<div class="section-title  text-center">
					<h2>Our Cars</h2>
					<span class="title-line"><i class="fa fa-car"></i></span>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
				</div>
			</div>
			<!-- Page Title End -->
		</div>
	</div>
</section>
<!--== Page Title Area End ==-->

<!--== Car List Area Start ==-->
<section id="car-list-area" class="section-padding">
	<div class="container">
		<div class="row">
			<!-- Sidebar Area Start -->
			<div class="col-lg-4">
				<div class="sidebar-content-wrap">
					<!-- Single Sidebar Start -->
					<div class="single-sidebar">
						<h3>For More Informations</h3>

						<div class="sidebar-body">
							<p>
								<i class="fa fa-mobile"></i> +8801816 277 243
							</p>
							<p>
								<i class="fa fa-clock-o"></i> Mon - Sat 8.00 - 18.00
							</p>
						</div>
					</div>
					<!-- Single Sidebar End -->

					<!-- Single Sidebar Start -->
					<div class="single-sidebar">
						<h3>Rental Tips</h3>

						<div class="sidebar-body">
							<ul class="recent-tips">
								<li class="single-recent-tips">
									<div class="recent-tip-thum">
										<a href="#"><img src="/assets/img/we-do/service1-img.png"
											alt="JSOFT"></a>
									</div>
									<div class="recent-tip-body">
										<h4>
											<a href="#">How to Enjoy Losses Angeles Car Rentals</a>
										</h4>
										<span class="date">February 5, 2018</span>
									</div>
								</li>

								<li class="single-recent-tips">
									<div class="recent-tip-thum">
										<a href="#"><img src="/assets/img/we-do/service3-img.png"
											alt="JSOFT"></a>
									</div>
									<div class="recent-tip-body">
										<h4>
											<a href="#">How to Enjoy Losses Angeles Car Rentals</a>
										</h4>
										<span class="date">February 5, 2018</span>
									</div>
								</li>

								<li class="single-recent-tips">
									<div class="recent-tip-thum">
										<a href="#"><img src="/assets/img/we-do/service2-img.png"
											alt="JSOFT"></a>
									</div>
									<div class="recent-tip-body">
										<h4>
											<a href="#">How to Enjoy Losses Angeles Car Rentals</a>
										</h4>
										<span class="date">February 5, 2018</span>
									</div>
								</li>

								<li class="single-recent-tips">
									<div class="recent-tip-thum">
										<a href="#"><img src="/assets/img/we-do/service3-img.png"
											alt="JSOFT"></a>
									</div>
									<div class="recent-tip-body">
										<h4>
											<a href="#">How to Enjoy Losses Angeles Car Rentals</a>
										</h4>
										<span class="date">February 5, 2018</span>
									</div>
								</li>
							</ul>
						</div>
					</div>
					<!-- Single Sidebar End -->

					<!-- Single Sidebar Start -->
					<div class="single-sidebar">
						<h3>Connect with Us</h3>

						<div class="sidebar-body">
							<div class="social-icons text-center">
								<a href="#" target="_blank"><i class="fa fa-facebook"></i></a> <a
									href="#" target="_blank"><i class="fa fa-twitter"></i></a> <a
									href="#" target="_blank"><i class="fa fa-behance"></i></a> <a
									href="#" target="_blank"><i class="fa fa-linkedin"></i></a> <a
									href="#" target="_blank"><i class="fa fa-dribbble"></i></a>
							</div>
						</div>
					</div>
					<!-- Single Sidebar End -->
				</div>
			</div>
			<!-- Sidebar Area End -->

			<!-- Car List Content Start -->
			<div class="col-lg-8">
				<div class="car-list-content m-t-50">
					<!-- Single Car Start -->
					<div class="single-car-wrap">
						<div class="row">
							<!-- Single Car Thumbnail -->
							<div class="col-lg-5">
								<div class="car-list-thumb car-thumb-1"></div>
							</div>
							<!-- Single Car Thumbnail -->

							<!-- Single Car Info -->
							<div class="col-lg-7">
								<div class="display-table">
									<div class="display-table-cell">
										<div class="car-list-info">
											<h2>
												<a href="#">Aston Martin One-77</a>
											</h2>
											<h5>39$ Rent /per a day</h5>
											<p>Vivamus eget nibh. Etiam cursus leo vel metus. Nulla
												facilisi. Aenean inorci luctus et ultrices posuere cubilia.</p>
											<ul class="car-info-list">
												<li>Air Condition</li>
												<li>Diesel</li>
												<li>Auto</li>
											</ul>
											<p class="rating">
												<i class="fa fa-star"></i> <i class="fa fa-star"></i> <i
													class="fa fa-star"></i> <i class="fa fa-star"></i> <i
													class="fa fa-star unmark"></i>
											</p>
											<a href="#" class="rent-btn">Book It</a>
										</div>
									</div>
								</div>
							</div>
							<!-- Single Car info -->
						</div>
					</div>
					<!-- Single Car End -->

					<!-- Single Car Start -->
					<div class="single-car-wrap">
						<div class="row">
							<!-- Single Car Thumbnail -->
							<div class="col-lg-5">
								<div class="car-list-thumb car-thumb-2"></div>
							</div>
							<!-- Single Car Thumbnail -->

							<!-- Single Car Info -->
							<div class="col-lg-7">
								<div class="display-table">
									<div class="display-table-cell">
										<div class="car-list-info">
											<h2>
												<a href="#">Aston Martin One-77</a>
											</h2>
											<h5>39$ Rent /per a day</h5>
											<p>Vivamus eget nibh. Etiam cursus leo vel metus. Nulla
												facilisi. Aenean inorci luctus et ultrices posuere cubilia.</p>
											<ul class="car-info-list">
												<li>Air Condition</li>
												<li>Diesel</li>
												<li>Auto</li>
											</ul>
											<p class="rating">
												<i class="fa fa-star"></i> <i class="fa fa-star"></i> <i
													class="fa fa-star"></i> <i class="fa fa-star"></i> <i
													class="fa fa-star unmark"></i>
											</p>
											<a href="#" class="rent-btn">Book It</a>
										</div>
									</div>
								</div>
							</div>
							<!-- Single Car info -->
						</div>
					</div>
					<!-- Single Car End -->

					<!-- Single Car Start -->
					<div class="single-car-wrap">
						<div class="row">
							<!-- Single Car Thumbnail -->
							<div class="col-lg-5">
								<div class="car-list-thumb car-thumb-3"></div>
							</div>
							<!-- Single Car Thumbnail -->

							<!-- Single Car Info -->
							<div class="col-lg-7">
								<div class="display-table">
									<div class="display-table-cell">
										<div class="car-list-info">
											<h2>
												<a href="#">Aston Martin One-77</a>
											</h2>
											<h5>39$ Rent /per a day</h5>
											<p>Vivamus eget nibh. Etiam cursus leo vel metus. Nulla
												facilisi. Aenean inorci luctus et ultrices posuere cubilia.</p>
											<ul class="car-info-list">
												<li>Air Condition</li>
												<li>Diesel</li>
												<li>Auto</li>
											</ul>
											<p class="rating">
												<i class="fa fa-star"></i> <i class="fa fa-star"></i> <i
													class="fa fa-star"></i> <i class="fa fa-star"></i> <i
													class="fa fa-star unmark"></i>
											</p>
											<a href="#" class="rent-btn">Book It</a>
										</div>
									</div>
								</div>
							</div>
							<!-- Single Car info -->
						</div>
					</div>
					<!-- Single Car End -->
				</div>

				<!-- Page Pagination Start -->
				<div class="page-pagi">
					<nav aria-label="Page navigation example">
						<ul class="pagination">
							<li class="page-item"><a class="page-link" href="#">Previous</a></li>
							<li class="page-item active"><a class="page-link" href="#">1</a></li>
							<li class="page-item"><a class="page-link" href="#">2</a></li>
							<li class="page-item"><a class="page-link" href="#">3</a></li>
							<li class="page-item"><a class="page-link" href="#">4</a></li>
							<li class="page-item"><a class="page-link" href="#">5</a></li>
							<li class="page-item"><a class="page-link" href="#">Next</a></li>
						</ul>
					</nav>
				</div>
				<!-- Page Pagination End -->
			</div>
			<!-- Car List Content End -->
		</div>
	</div>
</section>
<!--== Car List Area End ==-->