<section id="home-slider-area">
	<div class="home-slider-item slider-bg-1 overlay">
		<div class="container">
			<div class="row">
				<div class="col-lg-5">
					<br>
					<div class="book-a-car">
						<a href="<?php echo $this->url("login") ?>" class="btn btn-success btn-block">BOOK NOW</a>

					</div>
				</div>
				<div class="col-lg-12">
					<div class="slideshowcontent">
						<h1>BOOK A CAR TODAY!</h1>

						<p> FOR AS LOW AS <?php echo $this->myCurrency(1000) ?> </p>
						<p>
							<br>
							10% DISCOUNT
							FOR OUR RETURNING CUSTOMERS
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="home-slider-item slider-bg-2 overlay">
		<div class="container">
			<div class="row">
				<div class="col-lg-5">
					<br>
					<div class="book-a-car">
						<!-- <a href="<?php echo $this->url("login") ?>"
							class="btn btn-success btn-block">DOWNLOAD APP</a> -->
					</div>
				</div>
				<div class="col-lg-12">
					<div class="slideshowcontent">
						<h1>SEND A PARCEL</h1>
						<p></p>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- <div class="home-slider-item slider-bg-3 overlay">
            <div class="container">
                <div class="row">
                <div class="col-lg-5">
					<br> 
					<div class="book-a-car">
						<a href="<?php echo $this->url("login") ?>"
							class="btn btn-success btn-block">BOOK NOW</a>
					</div>
				</div>
                    <div class="col-lg-12">
                        <div class="slideshowcontent">
                            <h1>ENJOY YOUR JOURNEY</h1>
                            <p> </p>
                        </div>
                    </div>
                </div>
            </div>
        </div> -->
</section>



<!--== Book A Car Area Start ==-->
<div id="book-a-car">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="booka-car-content">
					<!-- <form action="index3.html">
                            <div class="pick-location bookinput-item">
							<input type="text"  placeholder="Pick Location" />
                            </div>

							<div class="car-choose bookinput-item">
							<input type="destination" placeholder="Destination" />
                            </div>

                            <div class="pick-date bookinput-item">
                                <input id="startDate2" placeholder="Pick Date" />
                            </div>

                            <div class="retern-date bookinput-item">
                                <input id="endDate2" placeholder="Return Date" />
                            </div>

                            

                            <div class="bookcar-btn bookinput-item">
                                <button type="submit">Book Car</button>
                            </div>
                        </form> -->
				</div>
			</div>
		</div>
	</div>
</div>
<!--== Book A Car Area End ==-->



<!--== Slider Area Start ==-->

<!--== Slider Area End ==-->



<!--== About Us Area Start ==-->
<!-- 	<section id="about-area" class="section-padding"> -->
<!-- 		<div class="container"> -->
<!-- 			<div class="row"> -->
<!-- Section Title Start -->
<!-- 				<div class="col-lg-12"> -->
<!-- 					<div class="section-title  text-center"> -->
<!-- 						<h2>About us</h2> -->
<!-- 						<span class="title-line"><i class="fa fa-car"></i></span> -->
<!-- 						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p> -->
<!-- 					</div> -->
<!-- 				</div> -->
<!-- Section Title End -->
<!-- 			</div> -->

<!-- 			<div class="row"> -->
<!-- About Content Start -->
<!-- 				<div class="col-lg-6"> -->
<!-- 					<div class="display-table"> -->
<!-- 						<div class="display-table-cell"> -->
<!-- 							<div class="about-content"> -->
<!-- 								<p>Lorem simply dummy is a texted of the printing costed and -->
<!-- 									typesetting industry. Lorem Ipsum has been the industry's -->
<!-- 									standard dummy text ever since the 1500s, when an unknown -->
<!-- 									printer took a galley of type.</p> -->

<!-- 								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. -->
<!-- 									Quasi aliquid debitis optio praesentium, voluptate repellat -->
<!-- 									accusantium deserunt eius.</p> -->
<!-- 								<div class="about-btn"> -->
<!-- 									<a href="#">Book a Car</a> <a href="#">Contact Us</a> -->
<!-- 								</div> -->
<!-- 							</div> -->
<!-- 						</div> -->
<!-- 					</div> -->
<!-- 				</div> -->
<!-- About Content End -->

<!-- About Video Start -->
<!-- 				<div class="col-lg-6"> -->
<!-- 					<div class="about-video"> -->
<!-- 						<iframe -->
<!-- 							src="https://player.vimeo.com/video/121982328?title=0&byline=0&portrait=0"></iframe> -->
<!-- 					</div> -->
<!-- 				</div> -->
<!-- About Video End -->
<!-- 			</div> -->
<!-- 		</div> -->
<!-- 	</section> -->
<!--== About Us Area End ==-->

<!--== Partner Area Start ==-->
<!-- 	<div id="partner-area"> -->
<!-- 		<div class="container-fluid"> -->
<!-- 			<div class="row"> -->
<!-- 				<div class="col-lg-12 text-center"> -->
<!-- 					<div class="partner-content-wrap"> -->
<!-- Single Partner Start -->
<!-- 						<div class="single-partner"> -->
<!-- 							<div class="display-table"> -->
<!-- 								<div class="display-table-cell"> -->
<!-- 									<img src="assets/img/partner/partner-logo-1.png" alt="JSOFT"> -->
<!-- 								</div> -->
<!-- 							</div> -->
<!-- 						</div> -->
<!-- Single Partner End -->

<!-- Single Partner Start -->
<!-- 						<div class="single-partner"> -->
<!-- 							<div class="display-table"> -->
<!-- 								<div class="display-table-cell"> -->
<!-- 									<img src="assets/img/partner/partner-logo-2.png" alt="JSOFT"> -->
<!-- 								</div> -->
<!-- 							</div> -->
<!-- 						</div> -->
<!-- Single Partner End -->

<!-- Single Partner Start -->
<!-- 						<div class="single-partner"> -->
<!-- 							<div class="display-table"> -->
<!-- 								<div class="display-table-cell"> -->
<!-- 									<img src="assets/img/partner/partner-logo-3.png" alt="JSOFT"> -->
<!-- 								</div> -->
<!-- 							</div> -->
<!-- 						</div> -->
<!-- Single Partner End -->

<!-- Single Partner Start -->
<!-- 						<div class="single-partner"> -->
<!-- 							<div class="display-table"> -->
<!-- 								<div class="display-table-cell"> -->
<!-- 									<img src="assets/img/partner/partner-logo-4.png" alt="JSOFT"> -->
<!-- 								</div> -->
<!-- 							</div> -->
<!-- 						</div> -->
<!-- Single Partner End -->

<!-- Single Partner Start -->
<!-- 						<div class="single-partner"> -->
<!-- 							<div class="display-table"> -->
<!-- 								<div class="display-table-cell"> -->
<!-- 									<img src="assets/img/partner/partner-logo-5.png" alt="JSOFT"> -->
<!-- 								</div> -->
<!-- 							</div> -->
<!-- 						</div> -->
<!-- Single Partner End -->

<!-- Single Partner Start -->
<!-- 						<div class="single-partner"> -->
<!-- 							<div class="display-table"> -->
<!-- 								<div class="display-table-cell"> -->
<!-- 									<img src="assets/img/partner/partner-logo-1.png" alt="JSOFT"> -->
<!-- 								</div> -->
<!-- 							</div> -->
<!-- 						</div> -->
<!-- Single Partner End -->

<!-- Single Partner Start -->
<!-- 						<div class="single-partner"> -->
<!-- 							<div class="display-table"> -->
<!-- 								<div class="display-table-cell"> -->
<!-- 									<img src="assets/img/partner/partner-logo-4.png" alt="JSOFT"> -->
<!-- 								</div> -->
<!-- 							</div> -->
<!-- 						</div> -->
<!-- Single Partner End -->
<!-- 					</div> -->
<!-- 				</div> -->
<!-- 			</div> -->
<!-- 		</div> -->
<!-- 	</div> -->
<!--== Partner Area End ==-->







<!--== Services Area Start ==-->
<section id="service-area" class="section-padding">
	<div class="container">
		<div class="row">
			<!-- Section Title Start -->
			<div class="col-lg-12">
				<div class="section-title  text-center">
					<h2>Our Services</h2>
					<span class="title-line"><i class="fa fa-car"></i></span>
					<p>Your secured and comfortable riding plug</p>
				</div>
			</div>
			<!-- Section Title End -->
		</div>


		<!-- Service Content Start -->
		<div class="row">


			<!-- Single Service Start -->
			<div class="col-lg-4 text-center">
				<div class="service-item">
					<i class="fa fa-cog"></i>
					<h3>LUXURY SERVICES</h3>
					<!-- 					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit -->
					<!-- 						admollitia.</p> -->
				</div>
			</div>
			<!-- Single Service End -->

			<!-- Single Service Start -->
			<div class="col-lg-4 text-center">
				<div class="service-item">
					<i class="fa fa-map-marker"></i>
					<h3>TAXI/MINI CAB</h3>
					<!-- 					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit -->
					<!-- 						admollitia.</p> -->
				</div>
			</div>
			<!-- Single Service End -->

			<!-- Single Service Start -->
			<div class="col-lg-4 text-center">
				<div class="service-item">
					<i class="fa fa-taxi"></i>
					<h3><?php echo strtoupper("Parcel/ Deliveries Service") ?></h3>
					<!-- 					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit -->
					<!-- 						admollitia.</p> -->
				</div>
			</div>
			<!-- Single Service End -->

			<!-- Single Service Start -->
			<!-- 				<div class="col-lg-4 text-center"> -->
			<!-- 					<div class="service-item"> -->
			<!-- 						<i class="fa fa-life-ring"></i> -->
			<!-- 						<h3>life insurance</h3> -->
			<!-- 						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit -->
			<!-- 							admollitia.</p> -->
			<!-- 					</div> -->
			<!-- 				</div> -->
			<!-- Single Service End -->

			<!-- Single Service Start -->
			<!-- 				<div class="col-lg-4 text-center"> -->
			<!-- 					<div class="service-item"> -->
			<!-- 						<i class="fa fa-bath"></i> -->
			<!-- 						<h3>car wash</h3> -->
			<!-- 						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit -->
			<!-- 							admollitia.</p> -->
			<!-- 					</div> -->
			<!-- 				</div> -->
			<!-- Single Service End -->

			<!-- Single Service Start -->
			<!-- 				<div class="col-lg-4 text-center"> -->
			<!-- 					<div class="service-item"> -->
			<!-- 						<i class="fa fa-phone"></i> -->
			<!-- 						<h3>call driver</h3> -->
			<!-- 						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit -->
			<!-- 							admollitia.</p> -->
			<!-- 					</div> -->
			<!-- 				</div> -->
			<!-- Single Service End -->
		</div>
		<!-- Service Content End -->
	</div>
</section>
<!--== Services Area End ==-->






<!--== Fun Fact Area Start ==-->
<!-- <section id="funfact-area" class="overlay section-padding"> -->
<!-- 	<div class="container"> -->
<!-- 		<div class="row"> -->
<!-- 			<div class="col-lg-11 col-md-12 m-auto"> -->
<!-- 				<div class="funfact-content-wrap"> -->
<!-- 					<div class="row"> -->
<!-- Single FunFact Start -->
<!-- 						<div class="col-lg-4 col-md-6"> -->
<!-- 							<div class="single-funfact"> -->
<!-- 								<div class="funfact-icon"> -->
<!-- 									<i class="fa fa-smile-o"></i> -->
<!-- 								</div> -->
<!-- 								<div class="funfact-content"> -->
<!-- 									<p> -->
<!-- 										<span class="counter">550</span>+ -->
<!-- 									</p> -->
<!-- 									<h4>HAPPY CLIENTS</h4> -->
<!-- 								</div> -->
<!-- 							</div> -->
<!-- 						</div> -->
<!-- Single FunFact End -->

<!-- Single FunFact Start -->
<!-- 						<div class="col-lg-4 col-md-6"> -->
<!-- 							<div class="single-funfact"> -->
<!-- 								<div class="funfact-icon"> -->
<!-- 									<i class="fa fa-car"></i> -->
<!-- 								</div> -->
<!-- 								<div class="funfact-content"> -->
<!-- 									<p> -->
<!-- 										<span class="counter">250</span>+ -->
<!-- 									</p> -->
<!-- 									<h4>CARS IN STOCK</h4> -->
<!-- 								</div> -->
<!-- 							</div> -->
<!-- 						</div> -->
<!-- Single FunFact End -->

<!-- Single FunFact Start -->
<!-- 						<div class="col-lg-4 col-md-6"> -->
<!-- 							<div class="single-funfact"> -->
<!-- 								<div class="funfact-icon"> -->
<!-- 									<i class="fa fa-bank"></i> -->
<!-- 								</div> -->
<!-- 								<div class="funfact-content"> -->
<!-- 									<p> -->
<!-- 										<span class="counter">50</span>+ -->
<!-- 									</p> -->
<!-- 									<h4>office in cities</h4> -->
<!-- 								</div> -->
<!-- 							</div> -->
<!-- 						</div> -->
<!-- Single FunFact End -->
<!-- 					</div> -->
<!-- 				</div> -->
<!-- 			</div> -->
<!-- 		</div> -->
<!-- 	</div> -->
<!-- </section> -->
<!--== Fun Fact Area End ==-->










<!--== Pricing Area Start ==-->
<!-- <section id="pricing-area" class="section-padding overlay"> -->
<!-- 	<div class="container"> -->
<!-- 		<div class="row"> -->
<!-- Section Title Start -->
<!-- 			<div class="col-lg-12"> -->
<!-- 				<div class="section-title  text-center"> -->
<!-- 					<h2>SERVICE DESCRIPTION</h2> -->
<!-- 					<span class="title-line"><i class="fa fa-car"></i></span> -->
<!-- 						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p> -->
<!-- 				</div> -->
<!-- 			</div> -->
<!-- Section Title End -->
<!-- 		</div> -->

<!-- Pricing Table Conatent Start -->
<!-- 		<div class="row"> -->
<!-- Single Pricing Table -->
<!-- 			<div class="col-lg-4 col-md-6 text-center"> -->
<!-- 				<div class="single-pricing-table"> -->
<!-- 					<h3>CAR RENTAL</h3> -->
<!-- 						<h2>$ 55.99</h2> -->
<!-- 					<h5>PER MONTH</h5> -->

<!-- 					<ul class="package-list"> -->
<!-- 						<li>FREE VEHICLE DELIVERY</li> -->
<!-- 						<li>WEDDINGS CELEBRATIONS</li> -->
<!-- 						<li>FULL INSURANCE INCLUDED</li> -->
<!-- 						<li>TRANSPORT ABROAD</li> -->
<!-- 						<li>ALL INCLUSIVE MINI BAR</li> -->
<!-- 						<li>CHAUFFER INCLUDED IN PRICE</li> -->
<!-- 					</ul> -->
<!-- 				</div> -->
<!-- 			</div> -->
<!-- Single Pricing Table -->

<!-- Single Pricing Table -->
<!-- 			<div class="col-lg-4 col-md-6 text-center"> -->
<!-- 				<div class="single-pricing-table"> -->
<!-- 					<h3>Trial</h3> -->
<!-- 					<h2>Free</h2> -->
<!-- 					<h5>PER MONTH</h5> -->

<!-- 					<ul class="package-list"> -->
<!-- 						<li>FREE VEHICLE DELIVERY</li> -->
<!-- 						<li>OTHER CELEBRATIONS</li> -->
<!-- 						<li>FULL INSURANCE</li> -->
<!-- 						<li>TRANSPORT ABROAD</li> -->
<!-- 						<li>MINI BAR</li> -->
<!-- 						<li>INCLUDED IN PRICE</li> -->
<!-- 					</ul> -->
<!-- 				</div> -->
<!-- 			</div> -->
<!-- Single Pricing Table -->

<!-- Single Pricing Table -->
<!-- 			<div class="col-lg-4 col-md-6 text-center"> -->
<!-- 				<div class="single-pricing-table"> -->
<!-- 					<h3>standard</h3> -->
<!-- 						<h2>$ 35.99</h2> -->
<!-- 					<h5>PER MONTH</h5> -->

<!-- 					<ul class="package-list"> -->
<!-- 						<li>DELIVERY AT AIRPORT</li> -->
<!-- 						<li>WEDDINGS AND OTHER</li> -->
<!-- 						<li>FULL INCLUDED</li> -->
<!-- 						<li>TRANSPORT ABROAD</li> -->
<!-- 						<li>ALL MINI BAR</li> -->
<!-- 						<li>CHAUFFER PRICE</li> -->
<!-- 					</ul> -->
<!-- 				</div> -->
<!-- 			</div> -->
<!-- Single Pricing Table -->
<!-- 		</div> -->
<!-- Pricing Table Conatent End -->
<!-- 	</div> -->
<!-- </section> -->
<!--== Pricing Area End ==-->








<!--== Testimonials Area Start ==-->
<!-- 	<section id="testimonial-area" class="section-padding"> -->
<!-- 		<div class="container"> -->
<!-- 			<div class="row"> -->
<!-- Section Title Start -->
<!-- 				<div class="col-lg-12"> -->
<!-- 					<div class="section-title  text-center"> -->
<!-- 						<h2>Testimonials</h2> -->
<!-- 						<span class="title-line"><i class="fa fa-car"></i></span> -->
<!-- 						<p>Lorem ipsum dolor sit amet elit.</p> -->
<!-- 					</div> -->
<!-- 				</div> -->
<!-- Section Title End -->
<!-- 			</div> -->

<!-- 			<div class="row"> -->
<!-- 				<div class="col-lg-8 col-md-12 m-auto"> -->
<!-- 					<div class="testimonial-content"> -->
<!--== Single Testimoial Start ==-->
<!-- 						<div class="single-testimonial"> -->
<!-- 							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis -->
<!-- 								totam obcaecati impedit, at autem repellat vel magni architecto -->
<!-- 								veritatis sed.</p> -->
<!-- 							<h3>Vongchong Smith</h3> -->
<!-- 							<div class="client-logo"> -->
<!-- 								<img src="assets/img/client/client-pic-1.jpg" alt="JSOFT"> -->
<!-- 							</div> -->
<!-- 						</div> -->
<!--== Single Testimoial End ==-->

<!--== Single Testimoial Start ==-->
<!-- 						<div class="single-testimonial"> -->
<!-- 							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis -->
<!-- 								totam obcaecati impedit, at autem repellat vel magni architecto -->
<!-- 								veritatis sed.</p> -->
<!-- 							<h3>Amader Tuni</h3> -->
<!-- 							<div class="client-logo"> -->
<!-- 								<img src="assets/img/client/client-pic-3.jpg" alt="JSOFT"> -->
<!-- 							</div> -->
<!-- 						</div> -->
<!--== Single Testimoial End ==-->

<!--== Single Testimoial Start ==-->
<!-- 						<div class="single-testimonial"> -->
<!-- 							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis -->
<!-- 								totam obcaecati impedit, at autem repellat vel magni architecto -->
<!-- 								veritatis sed.</p> -->
<!-- 							<h3>Atex Tuntuni Smith</h3> -->
<!-- 							<div class="client-logo"> -->
<!-- 								<img src="assets/img/client/client-pic-2.jpg" alt="JSOFT"> -->
<!-- 							</div> -->
<!-- 						</div> -->
<!--== Single Testimoial End ==-->
<!-- 					</div> -->
<!-- 				</div> -->
<!-- 			</div> -->
<!-- 		</div> -->
<!-- 	</section> -->
<!--== Testimonials Area End ==-->

<!--== Mobile App Area Start ==-->
<!-- <div id="mobileapp-video-bg"></div> -->

<section id="fmobile-app-area" class="overlay section-padding">
	<div id="mobile-app-area" class="container">
		<div class="row">
			<div class="col-lg-11 col-md-12 m-auto">
				<div class="funfact-content-wrap">
					<div class="row">
						<div class="col-lg-6">
							<div class="mobile-app-content">
								<h2>BAU LOGISTICS</h2>
								<p>Send a parcel within lagos for as low as &#8358;300 </p>
								<div class="app-btns">
									<a href="#"><i class="fa fa-android"></i> Android Store</a>
									<!-- 							 <a href="#"><i class="fa fa-apple"></i> Apple Store</a> -->
									<a href="https://api.whatsapp.com/send?phone=+2348052536443&text=Hi,%20I%20contacted%20you%20through%20BAU%20CARS%20website."><i class="fa fa-whatsapp">WhatsApp</i></a>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>
</section>






<!-- == Mobile App Area End == -->

<!--== Articles Area Start ==-->
<!-- 	<section id="tips-article-area" class="section-padding"> -->
<!-- 		<div class="container"> -->
<!-- 			<div class="row"> -->
<!-- Section Title Start -->
<!-- 				<div class="col-lg-12"> -->
<!-- 					<div class="section-title  text-center"> -->
<!-- 						<h2>Tips and articles</h2> -->
<!-- 						<span class="title-line"><i class="fa fa-car"></i></span> -->
<!-- 						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p> -->
<!-- 					</div> -->
<!-- 				</div> -->
<!-- Section Title End -->
<!-- 			</div> -->

<!-- Articles Content Wrap Start -->
<!-- 			<div class="row"> -->
<!-- Single Articles Start -->
<!-- 				<div class="col-lg-12"> -->
<!-- 					<article class="single-article"> -->
<!-- 						<div class="row"> -->
<!-- Articles Thumbnail Start -->
<!-- 							<div class="col-lg-5"> -->
<!-- 								<div class="article-thumb"> -->
<!-- 									<img src="assets/img/article/arti-thumb-1.jpg" alt="JSOFT"> -->
<!-- 								</div> -->
<!-- 							</div> -->
<!-- Articles Thumbnail End -->

<!-- Articles Content Start -->
<!-- 							<div class="col-lg-7"> -->
<!-- 								<div class="display-table"> -->
<!-- 									<div class="display-table-cell"> -->
<!-- 										<div class="article-body"> -->
<!-- 											<h3> -->
<!-- 												<a href="article-details.html">Wliquam sit amet urna eullam</a> -->
<!-- 											</h3> -->
<!-- 											<div class="article-meta"> -->
<!-- 												<a href="#" class="author">By :: <span>Admin</span></a> <a -->
<!-- 													href="#" class="commnet">Comments :: <span>10</span></a> -->
<!-- 											</div> -->

<!-- 											<div class="article-date"> -->
<!-- 												25 <span class="month">jan</span> -->
<!-- 											</div> -->

<!-- 											<p>Wlam aiber vestibulum fringilla oremedad ipsum dolor sit -->
<!-- 												amet consectetur adipisicing elit sed doned eiusmod tempored -->
<!-- 												incididunt ut labore et dolore magna aliquaa enimd ad minim -->
<!-- 												veniad.</p> -->

<!-- 											<a href="article-details.html" class="readmore-btn">Read More -->
<!-- 												<i class="fa fa-long-arrow-right"></i> -->
<!-- 											</a> -->
<!-- 										</div> -->
<!-- 									</div> -->
<!-- 								</div> -->
<!-- 							</div> -->
<!-- Articles Content End -->
<!-- 						</div> -->
<!-- 					</article> -->
<!-- 				</div> -->
<!-- Single Articles End -->

<!-- Single Articles Start -->
<!-- 				<div class="col-lg-12"> -->
<!-- 					<article class="single-article middle"> -->
<!-- 						<div class="row"> -->

<!-- Articles Thumbnail Start -->
<!-- 							<div class="col-lg-5 d-xl-none"> -->
<!-- 								<div class="article-thumb"> -->
<!-- 									<img src="assets/img/article/arti-thumb-2.jpg" alt="JSOFT"> -->
<!-- 								</div> -->
<!-- 							</div> -->
<!-- Articles Thumbnail End -->

<!-- Articles Content Start -->
<!-- 							<div class="col-lg-7"> -->
<!-- 								<div class="display-table"> -->
<!-- 									<div class="display-table-cell"> -->
<!-- 										<div class="article-body"> -->
<!-- 											<h3> -->
<!-- 												<a href="article-details.html">fringilla oremedad ipsum -->
<!-- 													dolor sit</a> -->
<!-- 											</h3> -->
<!-- 											<div class="article-meta"> -->
<!-- 												<a href="#" class="author">By :: <span>Admin</span></a> <a -->
<!-- 													href="#" class="commnet">Comments :: <span>10</span></a> -->
<!-- 											</div> -->

<!-- 											<div class="article-date"> -->
<!-- 												14<span class="month">feb</span> -->
<!-- 											</div> -->

<!-- 											<p>Wlam aiber vestibulum fringilla oremedad ipsum dolor sit -->
<!-- 												amet consectetur adipisicing elit sed doned eiusmod tempored -->
<!-- 												incididunt ut labore et dolore magna aliquaa enimd ad minim -->
<!-- 												veniad.</p> -->

<!-- 											<a href="article-details.html" class="readmore-btn">Read More -->
<!-- 												<i class="fa fa-long-arrow-right"></i> -->
<!-- 											</a> -->
<!-- 										</div> -->
<!-- 									</div> -->
<!-- 								</div> -->
<!-- 							</div> -->
<!-- Articles Content End -->

<!-- Articles Thumbnail Start -->
<!-- 							<div class="col-lg-5 d-none d-xl-block"> -->
<!-- 								<div class="article-thumb"> -->
<!-- 									<img src="assets/img/article/arti-thumb-2.jpg" alt="JSOFT"> -->
<!-- 								</div> -->
<!-- 							</div> -->
<!-- Articles Thumbnail End -->
<!-- 						</div> -->
<!-- 					</article> -->
<!-- 				</div> -->
<!-- Single Articles End -->

<!-- Single Articles Start -->
<!-- 				<div class="col-lg-12"> -->
<!-- 					<article class="single-article"> -->
<!-- 						<div class="row"> -->
<!-- Articles Thumbnail Start -->
<!-- 							<div class="col-lg-5"> -->
<!-- 								<div class="article-thumb"> -->
<!-- 									<img src="assets/img/article/arti-thumb-3.jpg" alt="JSOFT"> -->
<!-- 								</div> -->
<!-- 							</div> -->
<!-- Articles Thumbnail End -->

<!-- Articles Content Start -->
<!-- 							<div class="col-lg-7"> -->
<!-- 								<div class="display-table"> -->
<!-- 									<div class="display-table-cell"> -->
<!-- 										<div class="article-body"> -->
<!-- 											<h3> -->
<!-- 												<a href="article-details.html">Tempored incididunt ut labore</a> -->
<!-- 											</h3> -->
<!-- 											<div class="article-meta"> -->
<!-- 												<a href="#" class="author">By :: <span>Admin</span></a> <a -->
<!-- 													href="#" class="commnet">Comments :: <span>10</span></a> -->
<!-- 											</div> -->

<!-- 											<div class="article-date"> -->
<!-- 												17 <span class="month">feb</span> -->
<!-- 											</div> -->

<!-- 											<p>Wlam aiber vestibulum fringilla oremedad ipsum dolor sit -->
<!-- 												amet consectetur adipisicing elit sed doned eiusmod tempored -->
<!-- 												incididunt ut labore et dolore magna aliquaa enimd ad minim -->
<!-- 												veniad.</p> -->

<!-- 											<a href="article-details.html" class="readmore-btn">Read More -->
<!-- 												<i class="fa fa-long-arrow-right"></i> -->
<!-- 											</a> -->
<!-- 										</div> -->
<!-- 									</div> -->
<!-- 								</div> -->
<!-- 							</div> -->
<!-- Articles Content End -->
<!-- 						</div> -->
<!-- 					</article> -->
<!-- 				</div> -->
<!-- Single Articles End -->
<!-- 			</div> -->
<!-- Articles Content Wrap End -->
<!-- 		</div> -->
<!-- 	</section> -->
<!--== Articles Area End ==-->