<?php
echo $this->headtitle("Our Service");

?>
<!--== Page Title Area Start ==-->
<section id="page-title-area" class="section-padding overlay">
	<div class="container">
		<div class="row">
			<!-- Page Title Start -->
			<div class="col-lg-12">
				<div class="section-title  text-center">
					<h2>Our Services</h2>
					<span class="title-line"><i class="fa fa-car"></i></span>
					<p>Your secured and comfortable riding plug</p>
				</div>
			</div>
			<!-- Page Title End -->
		</div>
	</div>
</section>
<!--== Page Title Area End ==-->


<!--== Service Page Content Start ==-->
<section id="service-page-wrapper" class="section-padding">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<!-- Single Services Start -->
				<div class="single-service-item">
					<div class="service-item-thumb ser-thumb-bg-1"></div>
					<div class="service-item-content">
						<h3>CAR HIRE</h3>
						<p>Bau Cars provides services to both individuals and corporate
							bodies, locally and internationally.</p>
						<p>We also offers an array of vehicles at very affordable rates.</p>
						<p>At Bau cars Limited, we have experienced drivers that have good
							knowledge of road network anywhere in the country</p>
						<p>Bau Cars provides the best alternative to commuting and
							logistics through a strong network of high technological
							solutions that makes transportation accessible and affordable.</p>
					</div>
				</div>
				<!-- Single Services End -->

				<!-- Single Services Start -->
				<div class="single-service-item">
					<div class="service-item-thumb ser-thumb-bg-2 d-lg-none d-md-block"></div>
					<div class="service-item-content">
						<h3>LUXURY SERVICE</h3>
						<p>At Bau cars Limited, we don't do the regular car hiring. We
							provides a wide range of luxury services for your riding
							convenience. These Include
						
						
						<ul>
							<li><strong>Airport pick-up and drop off:</strong> we are just a click away, you
								can book your ride conveniently from within the country and
								anywhere around the world.</li>
							<li><strong>Schools runs drop off and pick up:</strong> we are your trusted riding
								partner, your information are safe with us. Integrity is our
								watchword.</li>
							<li><strong>Individual/Group tour booking:</strong> we also provides resort,
								beaches and holiday riding services.</li>

							<li><strong>Interstate services: </strong>our drivers, apart from being
								experienced, they also have a good knowledge of road networks
								within the country. We are your riding plug anywhere in the
								country.</li>
						</ul>
						</p>
						<p>Pre-booking/Reservation: our prospective riders can also book
							their trip in advance. The allows you to choose the desire date,
							time and location that works best with your schedule.</p>
					</div>
					<div
						class="service-item-thumb ser-thumb-bg-2 d-none d-lg-block d-md-none"></div>
				</div>
				<!-- Single Services End -->

				<!-- Single Services Start -->
				<div class="single-service-item">
					<div class="service-item-thumb ser-thumb-bg-3"></div>
					<div class="service-item-content">
						<h3>FLEET MANAGEMENT</h3>
						<p>This services is mainly for Corporate organisations outsourcing
							their land transportation requirements through a process of
							provision of cars by our company to the different categories of
							employees, pool vehicles, field /site operations, marketing
							mobility for a contractual period and at an agreed fixed monthly
							fees.</p>
						<p>Bau Cars fleet management entails the options of supplying of
							cars with the provision of drivers which exclusively cover;
							repairs & maintenance, Insurance, licensing /renewals, track
							devices and as well fuelling.</p>
						<p>
							<strong>BENEFITS OF FLEET MANAGEMENT SOLUTION </strong><br>The
							full Maintenance leasing will be an off balance sheet
							financing to the client, the monthly rental can be considered as
							an operating expense.
						</p>

						<p>Client will only pay a fixed cost for the duration of the
							lease; this will directly have a positive effect on the cash flow
							position of the organisation The full operating leasing will
							eliminate charging of depreciation against the lease vehicles
							hence, this will improve the company's assets and gearing ratios.</p>

						<p>The outsourcing process will allow the company to focus on its
							core function while efficiency will be driven by the outsourcing
							company from a scale advantage. Bau cars will always provide a
							monthly management reports which gives the client accurate fleet
							efficiency information.</p>

					</div>
				</div>
				<!-- Single Services End -->

				<!-- Single Services Start -->
				<div class="single-service-item">
					<div class="service-item-thumb ser-thumb-bg-4 d-lg-none d-md-block"></div>
					<div class="service-item-content">
						<h3><?php  echo strtoupper("Parcel/deliveries services")?></h3>
						<p>We handle your parcel and personal deliveries service in the
							most professional way. The 7Rs of logistics services which is
							getting the Right product, in the Right quantity, in the Right
							condition, at the Right place, at the Right time, to the Right
							customer, at the Right price is our watch word.</p>

					</div>
					<div
						class="service-item-thumb ser-thumb-bg-2 d-none d-lg-block d-md-none"></div>
				</div>
				<!-- Single Services End -->
			</div>
		</div>
	</div>
</section>
<!--== Service Page Content End ==-->




<!--== Partner Area Start ==-->

<!--== Partner Area End ==-->